### ISSUE TITLE
Enum types or constants or macros

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#10]
Some code I am porting uses enums. Something like the following would be nice.

```
type StatusType = { Invalid, OK, Queued };

type MessageType = (
    Status : StatusType
);

// inside a block

var m : MessageType;

m.Status = StatusType::Invalid;
```

Or, I could just use `int`, but then it would be nice to have constants or macros:

```
let StatusTypeInvalid = 0;
let StatusTypeOK = 1;
let StatusTypeQueued = 2;

type MessageType = (
    Status : int
);

// inside a block

var m : MessageType;

m.Status = StatusTypeInvalid;
```

**Comment by desaiankush** [comment]
I have faced similar problem in the past. I will discuss with Shaz if we
want to add it or there is a quick work around and let you know.

**Comment by shazqadeer** [comment]
@paulthomson: Do you need C-style constants or enumerated types?  C-style constants can be faked as follows:

fun Const(): int {
    return 2;
}

**Comment by desaiankush** [comment]
@paulthomson Did you figure this out ? What are you using ?

**Comment by paulthomson** [comment]
Yes! I am currently using functions. I guess enumerated types might be nice for type safety though.

**Comment by shazqadeer** [comment]
Enums have been added to P now.
