### ISSUE TITLE
Receive statement

### ISSUE THREAD

**Issue by teja5832** [p-org/P#102]
The regression tests 
P\Tst\RegressionTests\Feature2Stmts\Correct\receive6\receive6.p
P\Tst\RegressionTests\Feature2Stmts\Correct\receive12\receive12.p

say "This sample tests that a receive statement ignores the event handlers of the enclosing context."

Specifically, the receive statement on line 27, receive6.p handles the event E, but not F; however, it receives an F. I have two questions here:
a. Is the F simply dropped or deferred?
b. If there were an event G, **not**  registered to the state X of machine B, and it were received, would it be dropped too, or would it be a dynamic error?

Thanks

Teja

**Comment by shazqadeer** [comment]
a. F is deferred. The semantics of receive statement defers all events that are not explicitly handled by the received statement.

b. The event G, similar to the event F in the example, would stay in the queue.

**Comment by teja5832** [comment]
By extension, if there is no "case null", and the queue does not contain an event registered to the receive block, is it a runtime error?

**Comment by shazqadeer** [comment]
No, it is not.  The machine just blocks.
