### ISSUE TITLE
Updated documentation - the tutorial is outdated?

### ISSUE THREAD

**Issue by zvrba** [p-org/P#103]
I typed in PingPong example from "P tutorial" paper, only to get an error at `main machine Client`. By further experimentation I figured out that the "new" way to declare a main machine is to name it `Main`. The elevator example in the paper "P: Safe Asynchronous Event-Driven Programming" is even farther from the current syntax. In regression tests I see statements like `receive` and `announce` which are nowhere mentioned in either paper.

Is the updated documentation available somewhere?

**Comment by ankushdesai** [comment]
This has been fixed with the new Tutorial created by @ellab123
