### ISSUE TITLE
Concatenate seq

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#11]
It would be useful to be able to concatenate two `seq` values together.

E.g.
```
var s1 : seq[machine];
var s2 : seq[machine];
// ...


s1 = s1 + s2;
```

Currently, I have to do:

```
index = 0;
while(index < sizeof(s2))
{
  s1 += (sizeof(s1), s2[index]);
  index = index + 1;
}

```

...which I *think* is right. 
...except my variable names are much longer than `s1` and `s2`!

**Comment by desaiankush** [comment]
I have another suggestion which I have used.
You can put all these functions in a separate module as static functions
and use this module everywhere else just as a library.

**Comment by paulthomson** [comment]
Ah thanks this is very helpful.

However, I will be concatenating sequences of many different types. I guess I can't do a template/generic function? 

Should I just make a function that takes and returns `seq[any]`and then use `as`? How does `as` work (in the C version and zing version)? Is it like a runtime check?

**Comment by desaiankush** [comment]
Yes.
I have changed static functions a lot and I have only one example for it
checked in.
P\Tst\RegressionTests\ModuleSystem\staticfunction
You can look at this if it helps.

Public static functions can be accessed from other modules and private
static functions are internal to the current module.

I would suggestion, create a module HelperFunctions.

module HelperFunctions {

public fun ConcatSeq(s1: seq[any], s2:seq[any]) : seq[any]
{  }

}

you can call this function from other modules as:
(HelperFunctions::ConcatSeq(x, y)) as seq[int];

The type-checking for "as" is done dynamically in this case both for C and
Zing.
