### ISSUE TITLE
extern declarations for events

### ISSUE THREAD

**Issue by shazqadeer** [p-org/P#121]
My latest revision to the separate compilation feature for P associates events with compilation units so that the struct for each event can be generated along side the C code for the compilation unit.  This means that different compilation units cannot easily refer to each other's events.  The only way to do it would be split the events out into yet another compilation unit which is bad for software engineering.  We need extern event declarations similar to extern machine and function declarations.

**Comment by ankushdesai** [comment]
I agree with you that this would be a good thing to add to make the separate compilation feature complete.
I guess the way to go would be to add EventProto.

I like this design because otherwise, events have to be put into a separate file and referenced as compilation unit if they are shared across compilation units.

**Comment by shazqadeer** [comment]
Great, we have consensus then.  I will let you know if I manage to get to it.

**Comment by ankushdesai** [comment]
@shazqadeer: Whats the final call on this feature.

**Comment by shazqadeer** [comment]
We should add this feature.  It has low implementation complexity since code generation is not affected; only static analysis and summaries of compilation units are affected.  At the same time, the software engineering benefit is considerable.  However, I also think that this feature should be added only after the compiler and linker have been unified.

**Comment by ankushdesai** [comment]
We are planning to drop extern declarations from the language. 
Hence, closing this issue.
