### ISSUE TITLE
Add regressions for any<es>.

### ISSUE THREAD

**Issue by ankushdesai** [p-org/P#122]
Add regressions for any<es> both static and dynamic failures.
Static failure: https://github.com/p-org/P/blob/master/Src/Samples/regressions/anytype.p
Multiple Exports: https://github.com/p-org/P/blob/master/Src/Samples/regressions/interfacesubtype.p

**Comment by ankushdesai** [comment]
@shazqadeer 
I have also added a new type called "data" which represents any type but no with empty permission set.
We had to add this because we dont allow creating empty event sets.

**Comment by shazqadeer** [comment]
We should start adding the regression tests related to interfaces, sends, receives, etc. to the main suite of regression tests.

**Comment by shazqadeer** [comment]
@ankushdesai : Please take the lead on this issue.  Feel free to assign me to write test cases for specific features.

**Comment by ankushdesai** [comment]
No longer supported
