### ISSUE TITLE
numeric types

### ISSUE THREAD

**Issue by shazqadeer** [p-org/P#123]
C offers a whole set of number types, including
- float, double
- {unsigned, signed} * {8, 16, 32, 64}

It would be great if P offered these types.  Now that we have P -> C# and Zing will be eliminated, we can easily support all these types which are supported by C#.

**Comment by ankushdesai** [comment]
How about strings?

**Comment by shazqadeer** [comment]
Yes, strings would be a great addition.  They are not supported by C natively but they would be a very useful addition.

**Comment by shazqadeer** [comment]
In a private discussion, @ankushdesai  and I decided that adding this cross-product of numeric types is an overkill.  Instead, we will stick to the int type, interpret it as int64 for .NET and as either int32 or int64 for native based on how the runtime is compiled.  We will not add a string type at the moment.
