### ISSUE TITLE
structs

### ISSUE THREAD

**Issue by shazqadeer** [p-org/P#124]
All types in P are boxed, even primitive types like int, event, and bool.  This design means that tuples and named tuples of primitive types are not compatible C structs.  So, hardware buffers that are transferred over the "wire" must be martialed in order to pass into the P runtime, as opposed to a simple memcpy.  Interaction with hardware becomes expensive as a result.  What can we do to support interaction with hardware better?

**Comment by akashlal** [comment]
Why can't this be done using a foreign type and model functions for setting, getting and copying?

Akash

**Comment by ankushdesai** [comment]
I think we can provide a construct in P which resembles C struct.
We allow only primitive types like int, bool, etc in it.
The marshaling and unmarshalling of these types can then be done with memcpy etc.

**Comment by ankushdesai** [comment]
@akashlal 
I guess the question to consider is whether the programmer is fine with having these values as just foreign types?  Or he wants them to be stored in P types at some-point during execution.
If at some point the value stored in the foreign types flow into the P program and needs to be stored in P types then we will pay the price Shaz was talking about.

Otherwise, we can get away with foreign types.

Note that even the model functions getters and setters will have to do boxing and unboxing.

**Comment by shazqadeer** [comment]
I am talking about the situation where the programmer is not content with these structs as being uninterpreted.  In fact, she would like to write P code manipulated these values as structs/tuples.  In that case, modeling them as foreign types will not suffice.

**Comment by shazqadeer** [comment]
> I think we can provide a construct in P which resembles C struct.  We allow only primitive types like int, bool, etc in it.  The marshaling and unmarshalling of these types can then be done with memcpy etc.

I had the same idea but I have been struggling with a design decision: should we introduce a new type called "struct" or should we automatically infer any named-tuple that transitively contains inside it only primitive types as a "struct"?  I don't actually have a good idea of how the latter would work.

**Comment by ankushdesai** [comment]
It is better to have them be explicit for now  
In that case programmer will use structs whenever he is concerned about time and performance.

**Comment by ankushdesai** [comment]
@shazqadeer Closing this issue based on our last discussion
