### ISSUE TITLE
Minor mistake in section 3.3 of the manual

### ISSUE THREAD

**Issue by SolalPirelli** [p-org/P#126]
First, thanks for writing such a nice manual. :)

In section 3.3 of the manual, at the end of page 11, the description says "The monitor exits the hot `Init` state only when all nodes becomes empty".  
The sentence was clearly meant to reference the `Wait` state instead of `Init`.

Also, even more minor, in the same section, the indentation at the end of the `Wait` state of `Liveness` is wrong, and subsequently the state `Done` has wrong indentation as well.

**Comment by ankushdesai** [comment]
Not valid any more the manual has been discarded and moving to wiki slowly.
