### ISSUE TITLE
Slow compiling

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#13]
Using `pci` on `modp` branch.

I am just executing `load` and `test`, but they take a while:

`load`: 1min40 
`test`: 1min30

So at least 3min10 before I hit the next runtime error due to my mistakes :-)

**Comment by shazqadeer** [comment]
That is slow indeed.  It is surprising that the load time is longer than the test time.  The load time includes time only for type checking.  The test time includes time both for P to Zing translation and for zc to compile .zing to .dll.  The latter is known to be really slow.

How many LOC is the file?  Could you please send it to me privately?

**Comment by shazqadeer** [comment]
My recent refactoring of the Formula rules for the type checker and the compiler to C may have a positive effect. Please sync up and let me know if you see any difference.

**Comment by paulthomson** [comment]
This was on the modp branch. The master branch has always been better but your recent changes definitely help a lot, especially for P to C. 

```
9s [loading compiler]
>> 21s [type checking]
>> Writing stubs.c ...
Writing program.h ...
Writing program.c ...
46s [P to C]
>>
```

**Comment by desaiankush** [comment]
By how much did it help ?
What was the previous performance ?

**Comment by paulthomson** [comment]
That is good question! In a previous commit, the P to C compiler did not terminate within 10mins! But I think was some kind of regression (I don't think it always like that!).

**Comment by shazqadeer** [comment]
At one point in the master branch, I checked in a bug fix which had the unfortunate side effect of slowing down the compile of Paul's program to 10 minutes.  I have since refactored the rules both in the type checker and the P to C compiler to make the performance better.

**Comment by paulthomson** [comment]
Related: the reported time for P to C seems to be inaccurate, as if it does not include the time for the formula query.

**Comment by paulthomson** [comment]
The reported time seems incorrect for pci, P2C, master branch.

**Comment by shazqadeer** [comment]
@paulthomson : Do you understand the bug that is causing incorrect time to be reported?  Please point it out because the profiling looks correct to me.

**Comment by paulthomson** [comment]
@shazqadeer I cannot see a problem with the code and I cannot reproduce it!

**Comment by shazqadeer** [comment]
I am closing this issue for now.  Feel free to start a fresh issue for this problem.
