### ISSUE TITLE
Make binaries available

### ISSUE THREAD

**Issue by drewhk** [p-org/P#130]
This is a feature request to make pre-built binaries available for those who don't want to install VS and SDKs as they are rather heavyweight (I only need the C++ build tools).

**Comment by legowerewolf** [comment]
Could probably be done using CI.

**Comment by ankushdesai** [comment]
@zeynepsu your work on making package and release available through workflow will address this issue.

**Comment by ankushdesai** [comment]
@zeynepsu can you please close this issue with a link to the installation wiki.

**Comment by ankushdesai** [comment]
Please checkout the installation page in the wiki. Thank you!
