### ISSUE TITLE
P's swap keyword is unsound.

### ISSUE THREAD

**Issue by alexreinking** [p-org/P#138]
The following program subverts the type system by using the `swap` keyword to assign a `machine` to an `int` variable. This works with any two types.

```
machine Main {
    start state User_Init {
        entry {
            var a : int;
            var b : machine;

            a = 3;
            b = new Main();

            print "a = {0}\n", a;
            UnsafeAssign(a swap, b);
            print "a = {0}\n", a + 1;
        }
    }

    fun UnsafeAssign(a : any, b : any) : int {
        a = b;
        return 0;
    }
}
```

The following error is thrown at runtime, upon reaching the second `print` statement:

```
Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'P.Runtime.PrtInterfaceValue' to type 'P.Runtime.PrtIntValue'.
```

The key issue is that an additional check is required that the formal parameter type is a subtype of the actual argument type. But since the argument type has to be a subtype of the formal parameter type anyway, the two types must actually be *identical*.

**Comment by alexreinking** [comment]
A similar issue can be produced with named tuples:

```
machine Main {
    start state User_Init {
        entry {
            var a : (x: int);
            var b : (x: any);

            a = (x=3,);
            b = (x=false,);

            b = a swap;
            b.x = true;

            print "a.x + 1 = {0}", a.x + 1;
        }
    }
}
```
Even base-type variables are broken with swap:
```
machine Main {
    start state User_Init {
        entry {
            var a : int;
            var b : any;

            a = 3;
            b = false;

            b = a swap;
            b = true;

            print "a + 1 = {0}", a+ 1;
        }
    }
}
```

**Comment by ankushdesai** [comment]
I guess the solution is as you mentioned, make sure that are types are same wherever swap is used. Be it assignment or passing to functions.

**Comment by shazqadeer** [comment]
I would prefer not to change the static typing rules for swap assignments and parameter passing.  If you take a look at Tutorial\CoarseGrainedLocking sample, you will see that the typing flexibility is crucial.

a = b swap

Consider the statement above.  It is already checked that the static type of b is a subtype of the static type of a.  If, in addition, we introduce a runtime check (equivalent to a dynamic cast) that the dynamic type of value stored in a is a member of the static type of b, then the guarantee provided by P's type system will be restored.  This would be my preferred solution.

In addition to swap assignments, we also have to introduce a dynamic check for swap parameters when the called function returns.

**Comment by shazqadeer** [comment]
I would like to twist @ankushdesai's  arm to take this bug fix on.  It would be a forcing function to learn about the part of type system related to swap/move.  Let us see if there is push back :-).

**Comment by shazqadeer** [comment]
@ankushdesai : How about the following proposal:
1. Add a dynamic cast for swap assignments.
2. Enforce type equality for swap parameter passing in functions.

I am just going for simplicity of implementation.  As long as we allow swap assignments for different types, we do not lose any generality.

**Comment by ankushdesai** [comment]
I like the idea of dynamic cast. We already support it for float and interface types. 

I also like the idea of enforcing type equality at functions, less confusion and it would make code generation simple as well.

**Comment by shazqadeer** [comment]
I have fixed this problem.  Now P compiler reports static error on the first example and cast exceptions on the latter two.

**Comment by ankushdesai** [comment]
This bug has been fixed.
