### ISSUE TITLE
adding type machine<es>

### ISSUE THREAD

**Issue by shazqadeer** [p-org/P#139]
machine<es> is a more precise version of any<es>.  In addition to providing an upper bound on permissions stored in values, it also provides the guarantee that the value is a legal machine identifier.

**Comment by ankushdesai** [comment]
I will take care of this soon.

**Comment by shazqadeer** [comment]
I am closing this issue subsequent to the discussion yesterday.  The semantics mentioned for machine<es> in this issue is different from what we think we need.  A new issue will be opened later as needed.
