### ISSUE TITLE
[ModP] Interfaces as sets of events

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#14]
On modp branch. 

Edit:

* Allow interfaces in `sends`, `receives` and `po` declarations to denote a set of events.
* Allow e.g. the following: `po ITesterMachine > IReceiverMachine;`. 

Old: 
I can use interfaces in po declarations, but then zing fails to compile it. I have a non-minimal example if it would help. (Of course, it would be nice if this was actually supported! But right now I guess it is supposed to be a compile error!)

**Comment by shazqadeer** [comment]
We are trying to sort out the po stuff.  Hope to get something soon.

**Comment by shazqadeer** [comment]
Closing this issue.  ModP is going through a lot of changes including elimination of po.
