### ISSUE TITLE
eliminating model types and machines

### ISSUE THREAD

**Issue by shazqadeer** [p-org/P#141]
I would like to eliminate the notion of model types and machines from P, thereby also eliminating the notion of erasure.  Instead, we will introduce the notion of types and (global) functions without implementations in P.

type T;

fun Foo(x: int) : (int);

The above declarations indicate that the type T and function Foo are implemented in foreign code.  

The effect of model functions and types can be achieved by separating code containing "model" functions and types into a separate compilation unit.  Two different versions of this compilation unit are implemented, one with the type and function definition in P syntax and the other with type and function declarations as above with the implementations in foreign code.  Programmer has to take responsibility for compiling clients of the compilation unit against one or the other version.

The main reason to eliminate model functions and types is to simplify the P compiler.  These mechanisms were invented before P had separate compilation.  They feel needlessly complicated now.

**Comment by ankushdesai** [comment]
I agree that we don't need model type anymore.

model T = T';

The above behavior can be obtained by implementing T as T' when testing and as T in the actual implementation.

**Comment by shazqadeer** [comment]
Model types/functions/machines have been eliminated.
