### ISSUE TITLE
Test cases no longer valid P code

### ISSUE THREAD

**Issue by alexreinking** [p-org/P#143]
The following changes broke test cases.

1) The removal of model functions broke the code in ModP\..\OSRDriver.p, which uses them
2) The introduction of the `data` type keyword broke the following two files, which use variables named "data"
   * ModP\..\two-phase-commit.p
   * RegressionTests\F2\..\lock.p
3) Introducing the `float` type keyword broke Reg\F4\..\foreigntypes.p

**Comment by ankushdesai** [comment]
Thanks ! 
These have been fixed now.
