### ISSUE TITLE
Machine constructors allow passing arguments to no-argument machines.

### ISSUE THREAD

**Issue by alexreinking** [p-org/P#147]
It seems to me that the following program should not compile since we're creating the same machine with different arguments.

    extern machine M (/* int */);
    machine N {
        var my_m : machine;

        start state S {
            entry {
                my_m = new M(); // If we uncomment int above, the compiler complains about this line
                my_m = new M(3); // why does this compile without int?
            }
        }
    }

**Comment by ankushdesai** [comment]
This is allowed because no matter what you pass as an argument to the constructor the machine is never going to use it as it does not have any constructor argument in its start state.

You can make this rule stricter in your current implementation.

**Comment by alexreinking** [comment]
Does this apply to functions, too? Does the current implementation allow passing extra arguments to functions?

**Comment by ankushdesai** [comment]
No, it's not allowed for functions.
I see that it's asymmetric and may be not allowing such a thing would be a cleaner solution.

**Comment by alexreinking** [comment]
In the new implementation, I will enforce the "no extra arguments" rule uniformly.
