### ISSUE TITLE
Foreign code missing stubs

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#15]
When I compile a P program, I am getting some functions in `stubs.c` like:

```
void P_DTOR_ServerMachine_IMPL(PRT_MACHINEINST *context)
{
}
```
but there also some functions declarations in `program.h` that are not in `stubs.c`, like:

```
void P_SEND_OperationManagerMachine_IMPL(PRT_MACHINEINST *context, PRT_VALUE *evnt, PRT_VALUE *payload);
```

Is this intended?

Also, would this SEND function be executed when a send to this machine occurs (even if this machine has other events in its queue---does this machine have a queue)?

**Comment by shazqadeer** [comment]
The declaration for P_SEND_OperationManagerMachine_IMPL should be generated only if OperationManagerMachine is a model machine.  For actual execution, the logic for creating this machine and for handling events sent to it must be implemented in foreign code.  This particular function would be invoked whenever a non-model machine sends an event to an "instance" of the OperationManagerMachine.

**Comment by paulthomson** [comment]
Thank you that is helpful! To double check the stubs, here are the details:

The two machines are:

```
main machine ServerMachine ...
model OperationManagerMachine ...
```

The stubs:

```c
    void P_DTOR_ServerMachine_IMPL(PRT_MACHINEINST *context)
    {
    }

    void P_CTOR_ServerMachine_IMPL(PRT_MACHINEINST *context, PRT_VALUE *value)
    {
    }
```

The declarations:

```c
    void P_DTOR_ServerMachine_IMPL(PRT_MACHINEINST *context);

    void P_CTOR_ServerMachine_IMPL(PRT_MACHINEINST *context, PRT_VALUE *value);

    void P_DTOR_OperationManagerMachine_IMPL(PRT_MACHINEINST *context);

    void P_CTOR_OperationManagerMachine_IMPL(PRT_MACHINEINST *context, PRT_VALUE *value);

    void P_SEND_OperationManagerMachine_IMPL(PRT_MACHINEINST *context, PRT_VALUE *evnt, PRT_VALUE *payload);
```

**Comment by shazqadeer** [comment]
Yes, that is correct.  Although, it may not be the correct thing to dump out actual stub implementations for non-model machines.  You will have to make sure that you keep the actual stubs in a different folder to prevent them from being overwritten.  

I decided to generate stubs for non-model machines just for the convenience of testing the runtime against P examples without having to write C code.
