### ISSUE TITLE
a machine identifier with empty permission should be impossible in P

### ISSUE THREAD

**Issue by shazqadeer** [p-org/P#154]
I would like to propose that the P type checker make it impossible to create a machine identifier value whose permission is empty.   Three separate checks are needed to pull this off.

1. The statement "x = new I" is allowed only if the receive set of I is nonempty.  If the receive set of I is empty, the only possibility ought to be "new I" which creates an instance of I but does not allow a reference to the instance to be stored anywhere.

2. Inside the code of a machine with empty received set of events, it should not be possible to use the keyword "this".  Also, static global functions must not be allowed to access "this" ever; I believe this check is already implemented.

3. In the reduce expression (e to I), the receive set of I must be nonempty.

**Comment by alexreinking** [comment]
I will be sure to implement this check in the new compiler.

**Comment by ankushdesai** [comment]
@alexreinking can you please check if these checks are implemented.

**Comment by ankushdesai** [comment]
These have been taken care of correctly in the new compiler in SSA
