### ISSUE TITLE
What are .4ml files?

### ISSUE THREAD

**Issue by Maryam81609** [p-org/P#155]
Hi,

I see that the new version of P generates a foo.4ml file as a summary file which is used by plink. I did not find on the Internet what kind of files have .4ml extension. Is that a specific extension that is defined and used in P?

Thanks

**Comment by shazqadeer** [comment]
It is an internal format used by P.  It is actually a file that is processed by Formula which is used internally inside the P compiler.

**Comment by Maryam81609** [comment]
Thanks!
What language their code has been written in?

**Comment by shazqadeer** [comment]
The Formula system I am referring to is the following:  https://github.com/Microsoft/formula.

The .4ml files are input to the formula tool.

**Comment by Maryam81609** [comment]
Oh, I was not aware of that. Thank you so much!
