### ISSUE TITLE
P language integration to Visual Studio Code

### ISSUE THREAD

**Issue by dwaynebradley** [p-org/P#157]
Is there a plugin available for using P in VS Code? If not, does anyone have suggestions for an IDE to use for coding in P?

**Comment by ankushdesai** [comment]
We have syntax highlighting for P in VS code:
https://github.com/p-org/P/tree/master/Src/Tools/VSCode/msr-vscode-p

We do have something in Sublime as well:
https://github.com/p-org/Sublime-P

If you have suggestions for improvement let us know.

**Comment by dwaynebradley** [comment]
Awesome! Thank you @ankushdesai.
