### ISSUE TITLE
Finalize the P type system with respect to machines and interfaces

### ISSUE THREAD

**Issue by ankushdesai** [p-org/P#158]
There is one other proposal we should consider.  
It makes machine identifier types more verbose (and informative) but it has an elegance to it. 

> A machine identifier is a triple (I, n, p) where I is the name of the interface with which it was created (new I), n is the instance number and p is the associated permissions with the identifier.
> Permissions in an identifier control the set of events that can be sent to the target machine using the given identifier.

In this proposal, a machine identifier type is a pair from ({machine} U InterfaceName) \times EventSetName.  Syntactically, it could look like
```
 
machine[ES]
I[ES]
 
```
The idea is that I (or machine) provides information about the first component of the machine identifier and ES (event set name) provides information about the last component.  Thus, I[ES] means that the interface is I and permission is exactly ES and machine[ES] means the interface could be anything but the permission is exactly ES.  In this case, we could also have I be a shorthand for I[I.ReceiveSet].

An interface is declared as:

`interface I (<constructortype>) = { <set of received events>};`

If we all agree with and understand this part then I will define the sub-typing relation between these types.

@shazqadeer , @alexreinking

**Comment by shazqadeer** [comment]
In this proposal, how would I represent a type in which the permission set could be anything?

**Comment by ankushdesai** [comment]
I is a short hand for I[I.receiveset] similarly machine is the shorthand for machine[allEvents].

**Comment by shazqadeer** [comment]
I suspect it is not machine[allEvents] you are talking about but just machine.  machine[ES] means that the permission set is exactly ES but interface could be anything.  machine means that both interface and permission set could be anything.  Is my understanding correct?

**Comment by ankushdesai** [comment]
Yes, you are right. It should be "machine" that represents all interfaces with any permission set.

**Comment by shazqadeer** [comment]
Ok, so I should think of machine as the union type for all machine identifiers.

**Comment by ankushdesai** [comment]
Yes.

**Comment by shazqadeer** [comment]
In the current proposal, "I" is shorthand for I[I.ReceiveSet].  Another option is to consider "I" as the union type for all machine identifiers whose first component is I but says nothing about the permission set.  Which do we prefer and why?

**Comment by ankushdesai** [comment]
I think we should go with the case where I represents set of machine identifiers whose first component is I and the permissions can be anything (not necessarily a subset of I.Receiveset).
This is better as it is consistent with "machine".

**Comment by shazqadeer** [comment]
First, I detect some confusion in the previous message.  I[ES] means that the permission must be exactly ES and not a subset of ES.  Agreed?  Second, if we make I mean that nothing is known about the permission set, it is not "backward compatible" with the interpretation of I implemented currently. Are we ok with that?

**Comment by ankushdesai** [comment]
I[ES] means that the permission must be exactly ES and not a subset of ES. Agreed? 

> Yes.

If we make I mean that nothing is known about the permission set, it is not "backward compatible" with the interpretation of I implemented currently. Are we ok with that?

> Yes, we have to pay this price I guess, if we want to be symmetric with what "machine" means.

**Comment by ankushdesai** [comment]
This thing has been taken care off in the new compiler and hence closing the issue.
