### ISSUE TITLE
Eliminate any type

### ISSUE THREAD

**Issue by ankushdesai** [p-org/P#159]
This was a proposal made by Shaz in the past discussions.

Do we want to eliminate "any" type and replace it with union type in ML

declare an explicit union type
 
`type TypeUnion  =  t1 of T1 | t2 of T2 | t3 of T3;`

@shazqadeer @alexreinking

**Comment by shazqadeer** [comment]
Real type unions would be welcome.  But I wonder if the "any" type can really be dropped.  I remember the scenario where the code for a transport layer uses a datatype such as (e: event, v: any) to transport any event-payload pair.  Type unions will not help here.  We need dependent types.  Does ML have the equivalent of "any"?

**Comment by ankushdesai** [comment]
I take this proposal back.
Let us keep the "any" type around. 
We should create a separate proposal for union type after the type system stabilizes
