### ISSUE TITLE
Output filename parameter

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#16]
It might be nice to be able to set the output filename(s) from the P compiler. I.e. `program.c` could be `MyPSystem.c`. Or, at least, the files could be named the same as the original P file, as is the case with the output zing model. i.e. `Main.p` -> `Main.zing` -> `Main.dll` (on the main branch at least).

**Comment by paulthomson** [comment]
Also, perhaps it should be possible to only compile to C (and only compile to Zing) in preparation for getting the compiler to be called from MSBuild.

**Comment by shazqadeer** [comment]
@ellab123:  Suppose we implement Paul's suggestion of generating foo.c, foo.h, and stubs.c for the input file foo.p.  I believe that will break the current regression testing tool.  Would it be straightforward to patch it?

@paulthomson: Regarding the issue of compiling only to C or only to Zing, why not always compile to both?  Are you worried about the performance of the compiler?

**Comment by paulthomson** [comment]
If you add an (optional) output filename parameter then I assume you could avoid having to change much of the regression testing code.

I guess compiling to both is fine actually! Although performance is currently a concern. And perhaps there will be certain main P files that are not appropriate for use with Zinger (while other P files will be designed as test harnesses for use with Zinger). It also feels like a missing feature given that it is possible to do it from pci (I have a script that feeds input to pci instead of using pc because I just want to use zinger right now).

**Comment by shazqadeer** [comment]
I have  added an  option /outputFileName:<name>.  For pci.exe, this option must be passed as argument to load command.  If this option is not used, then <name> defaults to the name of the P file (without the .p extension) passed as argument to pc.exe or to the load command if pci.exe is being used.  The compiler will generate name.zing, name.dll, name.c, name.h, and stubs.c.
