### ISSUE TITLE
Clone method doesn't deep copy the P state

### ISSUE THREAD

**Issue by akashlal** [p-org/P#166]
We're trying to extend PTester with additional exploration strategies. It is handy to use the Clone method on StateImpl to copy the program state for backtracking. But it fails to do a deep copy. In particular, a `PrtMachineValue` keeps a pointer to the machine that it refers to, and this pointer is copied as-is in the Clone method. Thus, the resulting state still has pointers back to the original state. This isn't a problem right now for PTester because Clone is only used to make copies of the initial state, which likely doesn't have objects of this type. 

I see the following options and I'd like to get the opinion of the P team:
1. "Doing a Clone of an arbitrary `StateImpl` is too complex and we should stay away from it. " I'll have to rethink my algorithm then.
2. Make `PrtMachineValue` a dump object with just a scalar index value. The `StateImpl` will keep the mapping from these indices to the machine object. This will require a change in the Compiler (to do this lookup).
3. Change the Clone method of PrtValue to take a `StateImpl` argument, which will be the new state being generated.

I think option 2 is the cleanest but it needs changes to the compiler.

**Comment by ankushdesai** [comment]
I think the option (1) is preferable if sometime in the future we would also like to extend PTester with fingerprinting of the state, in which case we will have to support complete state-traversal anyway.

If we want a quick fix solution, then option (2) is clean but dumping into an object every time wouldn't that effect memory and time efficiency?
Maybe I didn't completely understand the dump object scheme. Can you please explain it?

**Comment by akashlal** [comment]
Ah, sorry, I didn't mean "dump object". I meant "dumb object", i.e., make PrtMachineValue just store an identifier (e.g., name of the machine) and not a pointer to the machine. 

I'm moving ahead with option 3 right now, because its the least amount of work for me. We can revisit this later.
