### ISSUE TITLE
Debugging into generated C# code

### ISSUE THREAD

**Issue by akashlal** [p-org/P#167]
I'm playing with `RVTutorial\CoffeeMachine` example. I've attached a debugger to PTester to step through the program execution. But I am unable to step into the generated code (Test0.dll, for example). It correctly loads Test0.pdb but somehow doesn't find symbol information in there. Have you tried doing this, for example, to debug the generated C# code?

**Comment by ankushdesai** [comment]
One way to get around this which I normally did was to create a test C# project and link the PTester against it.

**Comment by akashlal** [comment]
That's a good suggestion. Thanks. 

It would be good to figure out why the symbols don't get loaded properly, but at least I can make progress now.
