### ISSUE TITLE
Aliasing of locals in stack frames

### ISSUE THREAD

**Issue by akashlal** [p-org/P#168]
In the generated C# code, this is how a "call" looks like:
```
(parent).PrtPushFunStackFrame(AnonFun1, (currFun).locals);
```
This creates a new stack frame. But the locals (`currFun.locals`) are passed by reference. Because of this, the locals of all stack frames in the stack at any point of time are aliased. Is this aliasing intentional? 

Trouble is that `Clone` breaks this aliasing because it creates a fresh copy of the local vector when the stack is cloned. Thus, execution of a step from a StateImpl `s` does not match with the execution of a step from `s.Clone()`. I can modify `PrtPushFunStackFrame` to make a copy of the locals, but I don't know if the aliasing is actually required (in which case, the `Clone` method should preserve the aliasing).

**Comment by ankushdesai** [comment]
I am closing this issue for now as you are making progress with the state hashing and found a work around, I guess.
