### ISSUE TITLE
Build fails on Linux (using Mono)

### ISSUE THREAD

**Issue by thakkarparth007** [p-org/P#169]
I tried building P using MonoDevelop on Ubuntu. There were a bunch of minor errors that I fixed first (changing GPLEX45.exe to gplex45.exe etc -> most of them were naming related changes), but now I'm stuck on building the Compiler solution.

I get around 320 errors, and it mainly keeps failing because PParser class isn't found. I added a 'using Microsoft.Pc.Parser;' in every file where it made sense, but the build still fails because many symbols aren't found on `PParser`, like `IdenContext`, `ProgramContext`, (all `XContext` mainly). One more symbol - `PParserBaseVisitor` isn't found. Not sure what else is missing, as there are still around 320 errors. I grepped for those symbols, but I couldn't find their declarations anywhere in the source code. From what it looks like, they're supposed to be injected by Antlr, but never really worked with Antlr before.

I'm interested in getting it working on Mono. With some help I'll send a PR that'll make it work.

**Comment by ankushdesai** [comment]
Can you provide some more information about the error?

**Comment by alexreinking** [comment]
Sounds like the code generator isn't running for you. Since it runs for us, you should raise an issue with the antlr4cs project here: https://github.com/tunnelvisionlabs/antlr4cs

**Comment by rajasekharjs** [comment]
problem seems to be from the ikvm.exe. Using the native OpenJDK runtime worked for me

$ cd  packages/Antlr4.CodeGenerator.4.6.4/tools
$ mv ikvm.exe ikvm.exe.bak
$ ln -s `which java` ikvm.exe

**Comment by ankushdesai** [comment]
The master branch implements new Compiler that uses .Net Core.
This issue must be resolved now. Please reopen if you face any problems.
