### ISSUE TITLE
Named tuple field indexes in foreign code

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#17]
I think (but I may be wrong) that I will need to use magic numbers when accessing the values of named tuple types from foreign code.

This will be very hard to maintain if the tuple types change (in the P code). Also, I think I will be converting large, nested tuple types to structs and back quite a lot, so I will no doubt make some mistakes.

It looks like the structure of named tuples can be explored/discovered/confirmed at runtime. But there is no way to get rid of the magic numbers. Ideally, I would like something like this:

```c

	temp = PrtTupleGet(payload, _NT_INDEX_SettingsType_Id);
	// ...
	temp = PrtTupleGet(payload, _NT_INDEX_SettingsType_Message);
	

	temp = PrtTupleGet(temp, _NT_INDEX_HelloMessageType_Data);
	temp = PrtTupleGet(temp, _NT_INDEX_HelloDataType_Name);

```

assuming the following types in P (although there could be additional fields added at any time):

```
type SettingsType =
(
  Id : int,
  Message : HelloMessageType
);

type HelloMessageType = 
(
  Data : HelloDataType
);

type HelloDataType =
(
  Name : int
);
```

**Comment by shazqadeer** [comment]
This is a good idea.  I will look into implementing it.

**Comment by shazqadeer** [comment]
I have checked in support for this feature.  The enumerated constants look like

P_FIELD_INDEX_T_f

where T is the named tuple type and f is a field in T.
