### ISSUE TITLE
Problems occur during my building P on Windows

### ISSUE THREAD

**Issue by rgu01** [p-org/P#170]
**# Prerequisite**

I've installed Microsoft .NET 4.6, Visual Studio 2017 and Windows 10 SDK version 10.0.15063.0.

**# Problems**

After running command line: "bld\build.bat release x86", I got these errors: 

Build FAILED.

"C:\Users\rgu01\git\P\Ext\PSharp\PSharp.sln" (default target) (1) ->
"C:\Users\rgu01\git\P\Ext\PSharp\Source\AddOns\DataFlowAnalysis\DataFlowAnalysis.csproj" (default target) (2) ->
"C:\Users\rgu01\git\P\Ext\PSharp\Source\AddOns\DataFlowAnalysis\DataFlowAnalysis.csproj" (Build target) (2:2) ->
(ReportAssetsLogMessages target) ->
  C:\Program Files\dotnet\sdk\2.1.200\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(327,5)
: error : Assets file 'C:\Users\rgu01\git\P\Ext\PSharp\Source\AddOns\DataFlowAnalysis\obj\project.assets.json' not foun
d. Run a NuGet package restore to generate this file. [C:\Users\rgu01\git\P\Ext\PSharp\Source\AddOns\DataFlowAnalysis\D
ataFlowAnalysis.csproj]

"C:\Users\rgu01\git\P\Ext\PSharp\PSharp.sln" (default target) (1) ->
"C:\Users\rgu01\git\P\Ext\PSharp\Source\AddOns\DataFlowAnalysis\DataFlowAnalysis.csproj" (default target) (2) ->
"C:\Users\rgu01\git\P\Ext\PSharp\Source\AddOns\DataFlowAnalysis\DataFlowAnalysis.csproj" (Build target) (2:2) ->
(RunResolvePackageDependencies target) ->
  C:\Program Files\dotnet\sdk\2.1.200\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5)
: error : Assets file 'C:\Users\rgu01\git\P\Ext\PSharp\Source\AddOns\DataFlowAnalysis\obj\project.assets.json' not foun
d. Run a NuGet package restore to generate this file. [C:\Users\rgu01\git\P\Ext\PSharp\Source\AddOns\DataFlowAnalysis\D
ataFlowAnalysis.csproj]

"C:\Users\rgu01\git\P\Ext\PSharp\PSharp.sln" (default target) (1) ->
"C:\Users\rgu01\git\P\Ext\PSharp\Source\Core\Core.csproj" (default target) (3) ->
"C:\Users\rgu01\git\P\Ext\PSharp\Source\Core\Core.csproj" (Build target) (3:2) ->
(ReportAssetsLogMessages target) ->
  C:\Program Files\dotnet\sdk\2.1.200\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(327,5)
: error : Assets file 'C:\Users\rgu01\git\P\Ext\PSharp\Source\Core\obj\project.assets.json' not found. Run a NuGet pack
age restore to generate this file. [C:\Users\rgu01\git\P\Ext\PSharp\Source\Core\Core.csproj]

"C:\Users\rgu01\git\P\Ext\PSharp\PSharp.sln" (default target) (1) ->
"C:\Users\rgu01\git\P\Ext\PSharp\Source\Core\Core.csproj" (default target) (3) ->
"C:\Users\rgu01\git\P\Ext\PSharp\Source\Core\Core.csproj" (Build target) (3:2) ->
(RunResolvePackageDependencies target) ->
  C:\Program Files\dotnet\sdk\2.1.200\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5)
: error : Assets file 'C:\Users\rgu01\git\P\Ext\PSharp\Source\Core\obj\project.assets.json' not found. Run a NuGet pack
age restore to generate this file. [C:\Users\rgu01\git\P\Ext\PSharp\Source\Core\Core.csproj]

"C:\Users\rgu01\git\P\Ext\PSharp\PSharp.sln" (default target) (1) ->
"C:\Users\rgu01\git\P\Ext\PSharp\Source\TestingServices\TestingServices.csproj" (default target) (6) ->
"C:\Users\rgu01\git\P\Ext\PSharp\Source\TestingServices\TestingServices.csproj" (Build target) (6:2) ->
"C:\Users\rgu01\git\P\Ext\PSharp\Source\SchedulingStrategies\SchedulingStrategies.csproj" (default target) (7:2) ->
(ReportAssetsLogMessages target) ->
  C:\Program Files\dotnet\sdk\2.1.200\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(327,5)
: error : Assets file 'C:\Users\rgu01\git\P\Ext\PSharp\Source\SchedulingStrategies\obj\project.assets.json' not found.
Run a NuGet package restore to generate this file. [C:\Users\rgu01\git\P\Ext\PSharp\Source\SchedulingStrategies\Schedul
ingStrategies.csproj]

"C:\Users\rgu01\git\P\Ext\PSharp\PSharp.sln" (default target) (1) ->
"C:\Users\rgu01\git\P\Ext\PSharp\Source\TestingServices\TestingServices.csproj" (default target) (6) ->
"C:\Users\rgu01\git\P\Ext\PSharp\Source\TestingServices\TestingServices.csproj" (Build target) (6:2) ->
"C:\Users\rgu01\git\P\Ext\PSharp\Source\SchedulingStrategies\SchedulingStrategies.csproj" (default target) (7:2) ->
(RunResolvePackageDependencies target) ->
  C:\Program Files\dotnet\sdk\2.1.200\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5)
: error : Assets file 'C:\Users\rgu01\git\P\Ext\PSharp\Source\SchedulingStrategies\obj\project.assets.json' not found.
Run a NuGet package restore to generate this file. [C:\Users\rgu01\git\P\Ext\PSharp\Source\SchedulingStrategies\Schedul
ingStrategies.csproj]

    0 Warning(s)
    6 Error(s)

Then I tried the other way, compiling PLANG using Visual Studio, I got some errors too. Parts of them are listed as below:

error CS0246: The type or namespace name 'PSharpRuntime' could not be found (are you missing a using directive or an assembly reference?)
error CS0234: The type or namespace name 'PSharp' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
error CS0234: The type or namespace name 'PSharp' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
error CS0234: The type or namespace name 'PSharp' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
error CS0234: The type or namespace name 'PSharp' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
error CS0234: The type or namespace name 'PSharp' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
error CS0234: The type or namespace name 'PSharp' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
error CS0234: The type or namespace name 'PSharp' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
error CS0246: The type or namespace name 'Event' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'Event' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'Event' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'Monitor' could not be found (are you missing a using directive or an assembly reference?)

They look like quite simple problems but take some efforts to figure out. Could anyone help me here? Thanks.

**Comment by rgu01** [comment]
Hi, Thanks a lot. I've tried your method, deleted the entire "P" folder, run the VSD shell as administrator, get the bits again in VSD shell, build them in VSD shell. But still got the same errors:

Build FAILED.

"C:\Users\rgu01\git\P\Ext\PSharp\PSharp.sln" (default target) (1) ->
"C:\Users\rgu01\git\P\Ext\PSharp\Source\AddOns\DataFlowAnalysis\DataFlowAnalysis.csproj" (default target) (2) ->
"C:\Users\rgu01\git\P\Ext\PSharp\Source\AddOns\DataFlowAnalysis\DataFlowAnalysis.csproj" (Build target) (2:2) ->
(ReportAssetsLogMessages target) ->
  C:\Program Files\dotnet\sdk\2.1.200\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(327,5)
: error : Assets file 'C:\Users\rgu01\git\P\Ext\PSharp\Source\AddOns\DataFlowAnalysis\obj\project.assets.json' not foun
d. Run a NuGet package restore to generate this file. [C:\Users\rgu01\git\P\Ext\PSharp\Source\AddOns\DataFlowAnalysis\D
ataFlowAnalysis.csproj]

etc.

Then the second way, still the same error occurred again. Could you specify your solution? My OS is Windows 10. Thank you very much.

**Comment by rgu01** [comment]
@thomaswahl Thanks, Thomas. I've reinstalled my VS2017 adding more components in it and executed the command lines using your advice, as administrator. It succeeded, yet still don't know why did those errors happen. But thanks anyway. :-)

**Comment by thomaswahl** [comment]
Cool. I wouldn't have known what else to try.

**Comment by rgu01** [comment]
@thomaswahl My email address is rong.gu@mdh.se, it would be nice to have someone to discuss with. So if you want, please send me an email. :-)
