### ISSUE TITLE
(Named) tuple subtyping

### ISSUE THREAD

**Issue by alexreinking** [p-org/P#179]
@ankushdesai and I were discussing what the subtyping rules for named/unnamed tuples are / ought to be. I'm not entirely sure which cases are covered by tests, but which of the following _should_ be legal?

```
var x : (a : int, b : float);
var y : (a: any, b : float);
var z : (any, float);
var w : (b: any, a : float);
y = x; // (1) same names, agreeable types
z = x; // (2) discarding names, agreeable types
z = x as (any, float); // (3) discarding names via explicit cast, agreeable types
y = z; // (4) implicitly adding names, agreeable types
y = z as (a: any, b: float); // (5) explicitly adding names, agreeable types
w = y; // (6) implicitly replacing names, agreeable types
w = y as (b: any, a: float); // (7) explicitly replacing names, agreeable types
```

There might be a few odd cases I missed.

@shazqadeer - would appreciate your input.

**Comment by shazqadeer** [comment]
As far as I remember, two tuples are comparable iff
1. both are named with exactly the same sequence of names, or 
2. both are unnamed with the same length.

A tuple T is a subtype of U iff each component type in T is a subtype of the component type in the same position in U.


arable.  A tuple

**Comment by ankushdesai** [comment]
Resolved, using the old Tuple implementation of C#.
