### ISSUE TITLE
What is the default value of `any`?

### ISSUE THREAD

**Issue by alexreinking** [p-org/P#180]
What is the value of `x` in the following code?

```
var x : any;
print "{0}\n", x;
```

What about this?

```
var x : any;
x = null;
print "{0}\n", x;
```

Can I do this?

```
var x : any;
x = (null as machine) to event; // this is weird.
print "{0}\n", x;
```

It seems to me that `null` isn't a bottom value for both `event` and `machine`, it's a placeholder for either value. Either we have to introduce a third "`null`" for `any`, or we have to say "`null` is a machine/event, unless we can deduce statically that it is an event/machine".

**Comment by shazqadeer** [comment]
As far as I remember, the default value of any is null.  null is special value that is a member of both event and machine types.  Do you see a problem?  I did not follow your last example.

**Comment by alexreinking** [comment]
The last example is strange because a machine-to-event conversion only makes sense when the value is null. If you had:
```
var m : machine;
// ...
send this, m to event;
```
You would expect it to fail spectacularly at runtime. I would further suggest that this should be made illegal by the type system. If you want to do this, pass through `any` first `((null as machine) as any) to event`.

I think some extra consideration needs to be taken with how we characterize null from a type system perspective. You can't send a null event. Can you send the null machine a non-null event? If not, why do we consider `null` to be a part of either type, let alone both? It's mostly useful for checking if a variable has been initialized or as a sentinel value in a map that's being used as a cache.

Maybe we should do type inference on `null` to figure out whether each instance is an event or a machine and let the default value of `any` be one or the other, or a third special value. This is generally possible in all instances we care about:

```
var m : map[int, machine];
m += (4, null); // null :: machine can be inferred from type of LHS

var e : event;
assert null != e; // null :: event can be inferred from non-null type in binop

var m : machine;
if (m == null) { ... } // same as above

assert null (==|!=) null; // special case: replace with "true" / "false"

var a : any;
if (a == null) { ... } // if we let null :: machine by default, then this works.
```

**Comment by ankushdesai** [comment]
I agree with Alex. Apart from being used as default value for machine and event, there is real no use case of null. So we should completely drop the notion of null type and infer it's type based on usage.

**Comment by shazqadeer** [comment]
I think Alex's proposal boils down to (1) dropping the null type, (2) using type inference to assign either machine or event type to the null value, and (3) using the any type in case the type inference fails.  In particular, the null value stays and continues to be a member of both machine and event types.  Is my understanding correct?

**Comment by shazqadeer** [comment]
Is the design issue resolved here?  Just to be clear, I have no objection to dropping the null type.

**Comment by alexreinking** [comment]
I'm testing both designs and seeing what works better in practice... stay tuned...

**Comment by ankushdesai** [comment]
Resolved, using the old C# PrtValues implementation.
