### ISSUE TITLE
Map stack frames in Zing to P file

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#19]
This is a "nice to have feature", but not important. I am guessing it would require a new statement/annotation in Zing where you can state "we have now reached line X in file Y from which this file was derived". Like the [#line](https://msdn.microsoft.com/en-us/library/b5w2czay.aspx) directive in C/C++. 
 
E.g.

```
Stack trace:
    PRT_VALUE.PrtTupleSet (Main.zing, Line 28905) 
    MACHINE_MainMachine.SendUpdate (Main.zing, Line 3689) [Main.p, Main.SendUpdate, Line 341]
    MACHINE_MainMachine.AnonFun1 (Main.zing, Line 4358) [Main.p, Main.Init.entry, Line 103]
    MACHINE_MainMachine.ReentrancyHelper (Main.zing, Line 3481)
    MACHINE_MainMachine.RunHelper (Main.zing, Line 2464)
    MACHINE_MainMachine.Run (Main.zing, Line 2387)
    MACHINE_MainMachine.Start (Main.zing, Line 2364)

```

**Comment by shazqadeer** [comment]
@desaiankush: Do you have some way of attaching attributes to the stack frames printed out in Zing?

**Comment by shazqadeer** [comment]
We are freezing feature development in P to Zing path because the plan is to eliminate Zing from the P pipeline and go straight to C#.
