### ISSUE TITLE
compilation failed on Mac

### ISSUE THREAD

**Issue by shazqadeer** [p-org/P#191]
The build command "sh build.sh" is failing on Mac with the following output:

Time Elapsed 00:00:18.42
~/Source/P/Bld
~/Source/P/Bld ~/Source/P/Bld
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/xcode_10_fb.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/xcode_10_fb.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/xcode_10_fb.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/xcode_10_fb.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/shaz/Source/P/Bld/build
Scanning dependencies of target libhandler
--- Configuring build ---
use '--help' for help on configuation options.

--- Check system ---
Found gcc  (at /usr/bin)
C compiler 'gcc' found
Compiler target: x86_64-apple-darwin18.2.0
Normalize target ABI from x86_64 to amd64 (used on Linux, etc)

Configure for target: gcc, amd64-apple-darwin18.2.0

Found ar  (at /usr/bin)
found archiver: ar
The C compiler is C99 compliant.
The C++ compiler is C++11 compliant.
Assembly setjmp found for this ABI: 'asm/setjmp_amd64.s'
Jump buffer size: 72
Do not use linked exception frames for C++
Function strncat_s: not found
Function strerror_s: not found
Function alloca: found
Header stdbool.h: found

--- Configuration summary ---
System:
  target      : amd64-apple-darwin18.2.0
Build:
  c compiler  : gcc -std=c99 -pedantic -Wall 
  c++ compiler: g++ -std=c++11 -Wall 
  assembler   : gcc -Wall 
  linker      : gcc 
  archiver    : ar rcs

Use the following commands to build:
> make depend
> make

To run tests:
> make tests

Test release version:
> make tests VARIANT=release

use 'make help' for help
build variant: debug, configuration: gcc-amd64-apple-darwin18.2.0
src/exception.c:11:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^~~~~~~~~~
1 error generated.
make[3]: *** [depend] Error 1
make[2]: *** [Prt/CMakeFiles/libhandler] Error 2
make[1]: *** [Prt/CMakeFiles/libhandler.dir/all] Error 2
make: *** [all] Error 2
~/Source/P/Bld

Any ideas?

**Comment by ankushdesai** [comment]
Libhandler is failing. Can you go into libhandler submodule and do a make depend and make there. If it still fails. Please post issue on libhandler and Daan is really quick in helping out.

**Comment by ankushdesai** [comment]
@shazqadeer Is this issue fixed?

**Comment by shazqadeer** [comment]
There is an issue posted on libhandler page: https://github.com/koka-lang/libhandler/issues/8.  It has not been fixed yet.  I just reminded Daan

**Comment by shazqadeer** [comment]
I just heard that Daan has fixed the problem.

**Comment by ankushdesai** [comment]
@shazqadeer Can you please confirm that this issue has been resolved now.

**Comment by ankushdesai** [comment]
This issue has been fixed now.
