### ISSUE TITLE
P wiki is outdated and needs to updated to reflect the latest toolchain in master

### ISSUE THREAD

**Issue by shazqadeer** [p-org/P#192]

**Comment by suvamM** [comment]
I'd like to second this.
As an example (and maybe I am missing something here), I am following the build instructions, but pt.exe does not get generated. What is the method to build the PTester?

**Comment by ankushdesai** [comment]
PTester is not supported in the new compiler. The compiler generates P# code and you can use PSharpTester to test the program.
