### ISSUE TITLE
PrtTuple cannot be used with type arguments

### ISSUE THREAD

**Issue by suvamM** [p-org/P#198]
When sending a tuple as an event, the translation to `P#` has the following signature:

`new PrtTuple<PMachineValue, PrtInt>(TMP_tmp5_2, TMP_tmp6_2))(...)`

This throws the error `The non-generic type PrtTuple cannot be used with type arguments`. Classifying this as a (probable) bug.

**Comment by ankushdesai** [comment]
This has been fixed as well.
