### ISSUE TITLE
Issue in GotoStmt transation to P#

### ISSUE THREAD

**Issue by suvamM** [p-org/P#199]
The `GotoStmt` is handled as `currentMachine.GotoState(...)`, which throws an error, and should instead be `currentMachine.State(...)`. Classifying as a possible bug.

**Comment by ankushdesai** [comment]
I did not understand what the problem. It throws an exception and then the exception is then handled in a specific way to implement the P# semantics.

**Comment by suvamM** [comment]
I have a function in a liveness monitor as:

```
fun Foo () {
  if (b1) {
    goto HotState;
  }
  else {
    goto ColdState;
  }
}
```
which gets translated into 

```  
if (TMP_tmp1_9)
            {
                currentMachine.GotoState<Liveness.Imbalanced>();  // s1
                throw new PUnreachableCodeException();
            }
            else
            {
                currentMachine.GotoState<Liveness.Balanced>();  // s2
                throw new PUnreachableCodeException();
            }
```

results in an error in lines `s1` and `s2` saying "There is no argument given that corresponds to the required formal parameter payload of PMonitor.GotoState<T>(object)`. I'm sorry that the earlier description of the issue wasn't accurate.

**Comment by ankushdesai** [comment]
Got it. I will fix this and other issues.
Apologies for the delay.

**Comment by ankushdesai** [comment]
This must be fixed as well. Please re-open it if you face any problem.
Thanks for catching these errors.
