### ISSUE TITLE
Updating the P Event Types

### ISSUE THREAD

**Issue by ankushdesai** [p-org/P#202]
Shaz thinks that the P# design which bundles the event and the payload together is a superior design.  This needs to be discussed and flushed out.

**Comment by shazqadeer** [comment]
I would like to investigate whether both the event and machine types can be eliminated altogether.

**Comment by ankushdesai** [comment]
As per our last discussion, we agreed that we cannot eliminate event and machine types in P.

@shazqadeer Can you please describe your proposal of combining events and payloads with an example?

**Comment by shazqadeer** [comment]
Consider a program with the following event declarations:

event A(int);
event B(bool);
event C(int);

Currently, the event type can be thought of as an enum that contains A or B or C.  In the new system, the event type would be akin to a Rust enum with three variants corresponding to the three different events.  As a result, the following would change:

send m, e, v

would become

send m, e

where e would be an event value constructed in the same style as a Rust enum:

e = A(3);

Overall, we need event constructors and change the arity of send command.

**Comment by shazqadeer** [comment]
Also, remind me why we came to the conclusion that event and machine types cannot be eliminated.  My naive idea was that machine can be dropped because we have interfaces.  To drop event type, we need the capability to define a type that is a set of events.  Perhaps we already have event sets and we just need to elevate them to a type.

**Comment by ankushdesai** [comment]
@shazqadeer Thanks Shaz for the summary. I agree this will be useful.

We will have to extend `event` type to `event(type)` where `type` is the type of the payload. By default `event` means `event(any)` which represents a super-type of all events.

We need event type to represent a super type of events and same for machine type to represent a super type of all interface-types.

This is needed for example to implement a generic send function that forwards messages to the target machine.

`
fun Send(target: machine, mess: event(int))
`
Where send is a function of that takes a target machine and an event with payload of type int.

Also, regarding your comment about event-sets, yes, `event` is set of all events and `machine` is a set of all `interfaces` or `permissions`.

At some-point we can add a way in which users can define `union types`.

**Comment by shazqadeer** [comment]
https://github.com/p-org/P/issues/214

I have proposed a design for generics above where I address your challenge of writing a generic Send function.  I argue there that machine and event types can indeed be eliminated.  Take a look and let me know what you think.

**Comment by ankushdesai** [comment]
@shazqadeer  With the recently experience of using P inside Amazon. I agree with your assessment that it would be better to completely drop machine and event types. This will make P more strongly typed. Programmers generally use machine names as types instead of `machine`.

Lets add support for generics in P which will help eliminate these types!
