### ISSUE TITLE
Remove the linear types from the current implementation [Clean up!]

### ISSUE THREAD

**Issue by ankushdesai** [p-org/P#203]
The design of swap and move was done by @shazqadeer and there is lots of scope of improvement by taking inspiration from Rust and other frameworks.

Comments from Shaz:

> With swap, we actually have the capability to get arbitrary number of output parameters from functions.  So, I would like to revisit the design of functions as follows.  If a function returns a value, I would like to consider it as a pure function with no side effects.  If a function does not return a value, then it is a procedure with potential side effects.  Procedures can return values through swap parameters. This design will make sure that expressions do not have side effects.

**Comment by ankushdesai** [comment]
@exists-forall. You know details about the P linear type system using `move` and `swap`. 
I did describe to you its short-comings with respect to nested types.

It would be good if we can re-design the linear-type system in P. 
Please let us know if you have any suggestions based on your experience with Rust.

**Comment by ankushdesai** [comment]
The current changes in the compiler has broken the linear types implementation in P. We do not have users for linear types in P right now and will revisit it later.

**Comment by shazqadeer** [comment]
You should not let linear types in P get in your way.  It was an experimental feature that should be rethought and reimplemented.  You should consider deleting this feature from P to increase your velocity.

**Comment by shazqadeer** [comment]
Let me expand on my previous remark.  As far as I understand, P is currently being used only as a modeling language and not as an implementation language.  Linear types, as implemented in P, do not provide any modeling benefit.  They provide some implementation efficiency but the solution is nowhere near as comprehensive as the nearest competitor Rust.  So, overall I feel that the current design must be abandoned.  In future, if we want to move P towards a language in which implementation can also be done, then we have to revisit.

**Comment by ankushdesai** [comment]
Thanks @shazqadeer. Yes, lets revisit this sometime in the summer!

**Comment by ankushdesai** [comment]
Thanks @shazqadeer. Yes, lets revisit this sometime in the summer!

**Comment by ankushdesai** [comment]
Based on @shazqadeer feedback. We are currently using P only as a modeling language. Its worth removing linear types completely from the compiler and cleaning it up.

**Comment by ankushdesai** [comment]
Linear types have been completely removed from the compiler implementation.
We will add support for it when P gets used as an implementation language :)
