### ISSUE TITLE
Building and Testing P applications on Linux Platform

### ISSUE THREAD

**Issue by ankushdesai** [p-org/P#205]
We would like to improve the Build System for P for the Linux Platform.

What should we use as a build system for P programs which would involve compiling P files, and then compiling the generated code both C and P# with the corresponding foreign code to generate the executable files.

Any suggestions given your experience, @alexreinking @pdeligia @thisiscam .

**Comment by alexreinking** [comment]
I would use CMake for C/C++ programs that want to use P's C backend and msbuild for P# via .NET Core. If you don't like CMake, then a set of standard Makefile rules users can include to call the compiler would be helpful.
