### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by elmasasa** [p-org/P#206]
To generate files used by the PTester for systematic testing, P program has to be compiled into C#.

When the following command runs:

pc.exe /generate:C# foo.p bar.p /t:foo.4ml

the following files are generated (provided there's no static errors): foo.cs and foo.4ml.

When I follow this:
C:\Users\10719>Desktop\git\P\Bld\Drops\Release\Binaries\win-x64\publish\Pc/generate:C# PingPong.p/t:PingPong.4ml

The output is as bellow:
Illegal P file name  or file  not found
Illegal P file name  or file  not found
At least one .p file must be provided
USAGE: Pc.exe file1.p [file2.p ...] [-t:tfile] [options]
    -t:tfile                   -- name of output file produced for this compilation unit; if not supplied then file1
    -outputDir:path            -- where to write the generated files
    -generate:[C,P#]           -- select a target language to generate
        C   : generate C code using the Prt runtime
        P#  : generate C# code using the P# runtime
    -sourcemaps[:(true|false)] -- enable or disable generating source maps
                                  in the compiled output. may confuse some
                                  debuggers.
    -h, -help, --help          -- display this help message

PS:I found the PingPong.p from "git\P\Src\Samples\PingPong" and I have downloaded it to my computer.

Another problem that bothers me is what's the relationship between P and Psharp?

**Comment by ankushdesai** [comment]
Hi @elmasasa,

The documentation for P is out of date and will be updated soon to be in sync with the new compiler.

The new P compiler generates PSharp code and uses PSharp for systematic testing of P programs.

Please refer to the PSharp repo to learn more about it.

**Comment by ankushdesai** [comment]
@SelectricSimian Please address this issue after you are done updating the wiki page, Thanks!
