### ISSUE TITLE
Shared Memory Concurrency in P

### ISSUE THREAD

**Issue by ankushdesai** [p-org/P#207]
@shazqadeer There seems to be a lot of interest in enabling shared memory concurrent in P. Do you have any thoughts and ideas from your experience applying P/P# inside Azure?

@pdeligia @akashlal I see that PSharp supports shared memory concurrency analysis in some forms. Can you point me to relevant documentation and how should we model it in P so that we can analyze it using PSharp with the existing support, any ideas?

**Comment by shazqadeer** [comment]
The straightforward way to model shared-memory is as a P machine that encapsulates the shared data structure.  Operations on the data structure are modeled as events sent to this machine.  If an operation returns a value, that is modeled by sending an event back to the sender.
