### ISSUE TITLE
Inconsistent naming convention

### ISSUE THREAD

**Issue by shazqadeer** [p-org/P#21]
The name of PrtForeignValueToString does not match the convention of the rest of the foreign type related functions.

PRT_FORGN_MKDEF PrtMkDefaultForeignValue = &MkDefaultForeignValue;
PRT_FORGN_CLONE PrtCloneForeignValue = &CloneForeignValue;
PRT_FORGN_FREE PrtFreeForeignValue = &FreeForeignValue;
PRT_FORGN_GETHASHCODE PrtHashForeignValue = &HashForeignValue;
PRT_FORGN_ISEQUAL PrtIsEqualForeignValue = &IsEqualForeignValue;
PRT_FORGN_TOSTRING PrtForeignValueToString = &ToStringForeignValue;

**Comment by desaiankush** [comment]
Fixed
