### ISSUE TITLE
Adding Generics to P

### ISSUE THREAD

**Issue by ankushdesai** [p-org/P#214]
To make it easier to write real-world applications in P.
It would be good to support generics in P as specially for the foreign types.

@shazqadeer working on the initial design :)

**Comment by shazqadeer** [comment]
Here is an initial proposal.  

1. We would allow type parameters on top-level declarations such as type declarations, function declarations, and machine declarations. 

type T<X, Y> = (x: X, y: Y)

machine Foo<X, Y> {
    var x: X;
    var y: Y;
    ....
    fun foo(v: X) { ... }
} 

fun F<X>(v: X) { ... }

2.  Introduce eventsets as first-class types

type ES = {e1, e2, ...}

which allows us to provide types for variables whose runtime value is an event.

var ev: ES

2. machine is no longer a type.  Rather, it is a type constructor which takes a single type argument---an eventset type.

var m: machine<ES>

indicates a machine whose receive set is a superset of ES.

3. Type parameters may be constrained by a kind.  Currently, we only need one kind "eventset" that represents the set of all eventset types.

GenericSend<T: eventset>(m: machine<T>, ev: T)

4. An interface is *not* a type. The only purpose of an interface declaration is to facilitate module construction and machine linkage.  An interface declaration is simply an interface name and two types, an ordinary value type and an eventset type.

interface I(T) receives ES

In our examples, whenever we have felt the need to use I as a type, we could instead use machine<ES>.

Does this sound reasonable?

Comments?

**Comment by ankushdesai** [comment]
Based on the current usage pattern a better approach is to just let programmers define complex types in foreign code. 
We have not seen a real demand for this feature yet. 

Closing it for now and can re-open if the discussion comes up again :)
