### ISSUE TITLE
Separate Compilation in P

### ISSUE THREAD

**Issue by ankushdesai** [p-org/P#216]
It would good to enable separate compilation for P that allows decomposing the implementation into separate P projects.

Enabling this for C pipeline seems hard and we can ignore it.
I think enabling it for the P# pipeline would be of value and shouldn't be that hard.

@alexreinking Please let us know if you have any thoughts and idea around this?

**Comment by alexreinking** [comment]
Definitely seems doable for C#. I'll gather some of my thoughts on it in a bit.

**Comment by ankushdesai** [comment]
Will re-open this issue when the demand peaks again :)
