### ISSUE TITLE
Equality of foreign type aliases

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#22]
This assertion fails in Zinger. Should it?

Eq.p:
```
type F;
type G = F;


main machine MyMachine
{
    start state Init
    {
        entry
        {
            var f : F;
            var g : G;

            assert f == g;
        }
    }

}
```

**Comment by paulthomson** [comment]
Also, I cannot do:

```
g = fresh(G);
```

I get a compile error: `Illegal type`.

**Comment by shazqadeer** [comment]
I am working on it.

**Comment by paulthomson** [comment]
Cool! This is no longer a blocking issue for me right now---I removed my "G" from the set of types as it wasn't really needed.

**Comment by shazqadeer** [comment]
I have checked in fixes to both bugs mentioned by you.
