### ISSUE TITLE
Implement set type in P

### ISSUE THREAD

**Issue by ankushdesai** [p-org/P#225]
Based on the recent experience and use case. It would be great if we can support `string` and `set[type]` types in P.

**Comment by ankushdesai** [comment]
We would like to add a set type. 
The set type will be parameterized with the type of elements in the set.
`var s: set[int]`  declares a set of type int.

The operations allowed on set are the same as those allowed on map.

`+=` to add to set (if the element already exist, ignore), `-=` remove the element, `in` contains operation on the set. `s[i]` returns the `i`th element in the set. This will allows us to iterate over the set as well (order does not matter).

@Eric-Le-Ge Please let me know if there are any questions.

@shazqadeer comments?

**Comment by akashlal** [comment]
What data-structure do you plan to use for implementing this set? It seems that the combination of indexing, insertion and membership, all together can't be done efficiently (log time). Usually, set data structures have an enumerator to iterate over its contents (and no direct indexing).

**Comment by ankushdesai** [comment]
I wanted to add indexing because P does not support iterator over collection types.
But you made a valid point, I have edited my comment and will add iterator for collection types in P separately. Thanks!

**Comment by ankushdesai** [comment]
Thanks to @Eric-Le-Ge, this part of master now #230
