### ISSUE TITLE
Running P on Ubuntu

### ISSUE THREAD

**Issue by jzhang919** [p-org/P#227]
Hi all: 

How do you verify P programs on Linux? I've successfully built the compiler and the runtime libraries, and can build the Hello example. But I don't know how to verify the C or C# program generated. I know from [@192](https://github.com/p-org/P/issues/192) that P no longer uses PTester.exe, and it seems that we should use the P# Tester. 

Do I need to build P# from source/use NuGet on Linux to get the P# Tester? Both approaches seem to rely on Windows Powershell. Or should I be using a different tool to verify P programs?

**Comment by pdeligia** [comment]
Hi @jzhang919, P# works on Linux via `dotnet core` which is multiplatform (e.g. to run the tester you would do `dotnet <somepath>\netcoreapp2.1\PSharpTester.dll <somecommands>`.

We currently do not have a non-powershell script for building the source code on Linux, but powershell itself is multiplatform (https://github.com/powershell/powershell) and can be easily installed to run the scripts. The P# `csproj` should only build `dotnet core` binaries under Linux.

However, you do not need to build P# from source, as you can easily install the package via NuGet, which includes the P# tester. There are quite a few tutorials/docs that show how to install Nuget Packages in Linux (e.g. https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools).

**Comment by ankushdesai** [comment]
@jzhang919  You will be able to find the `PSharpTester.dll` in the nuget packages folder.

Please let us know if you face any problem running PSharpTester on the generated code.

**Comment by ankushdesai** [comment]
Issue has been resolved.
