### ISSUE TITLE
Cannot raise in functions

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#23]
All my event handlers are functions. This avoids code duplication. Also, the event handlers are quite large and call other functions. But I cannot use raise in a function. So, if I want to use raise, I will have to work around this, perhaps by awkwardly making every function return an event? And then making every event handler check the return value and possibly raise. 

I guess the issue is that raise ends execution of the handler. So, if raise was allowed in functions, one would have to assume that every function call could in fact terminate the event handler which would be very strange (kind of like exceptions perhaps?).

But raise is really just (equivalent to) two operations: insert an event at the front of my queue and then return. But we can't access the useful operation (the insert) without having to return. Could we perhaps have the "insert at front of my queue" operation available on its own, without complicating things by forcing a return? This way, I could add an event at the front of my queue from functions without causing any issues or confusion. Otherwise, I can't use this useful (and efficient*) operation (and only because it is stuck to another operation!). 

\*because, unlike sending an event to myself, it is not a scheduling point, right?

**Comment by paulthomson** [comment]
Actually, perhaps I could work around this by having a field: `var RaisedEventV : event;`
and then checking this at the end of every event handler. Slightly better, but still a bit silly!

**Comment by desaiankush** [comment]
I have used the trick you mentioned above in most of the cases. I think its
not that bad :)

**Comment by paulthomson** [comment]
I was wrong! Raise is allowed in functions! Just not when transitioning to another state!
