### ISSUE TITLE
Add support for string types in P

### ISSUE THREAD

**Issue by Eric-Le-Ge** [p-org/P#234]
Currently P supports strings in print statements
`print "values ({0}, {1})", val1, val2;`
We would like to add support for string concatenation and equality comparison:
`s = s1 + s2 //concatenation, assigns s to new string`
`b = s1 == s2 //comparison, assigns b to boolean`
The string type would be treated as primitive data types, so `s1==s2` would be true as long as their contents are equal.

**Comment by ankushdesai** [comment]
Thanks @Eric-Le-Ge !
Can we also add initialization like below:
`s = "my name is: {0}, {1}", firstName, lastName;`

**Comment by ankushdesai** [comment]
Done in #237 !!

**Comment by ankushdesai** [comment]
Reopening this issue as we would like to add support for other binary comparison operations like "<", "<=", ...

**Comment by ankushdesai** [comment]
Fixed in the https://github.com/p-org/P/pull/243. Thanks @Eric-Le-Ge
