### ISSUE TITLE
Tentative definition in generated C code

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#26]
Found by Richard. 

At the end of the generated file `program.h` there is:

```
PRT_PROGRAMDECL P_GEND_PROGRAM;
```

This is a definition and so any file that includes `program.h` is defining its own copy of `P_GEND_PROGRAM`. "Luckily", most C compilers allow "tentative definitions" and so will treat these as declarations. But C++ compilers do not allow this, so this should fixed to:

```
extern PRT_PROGRAMDECL P_GEND_PROGRAM;
```

**Comment by shazqadeer** [comment]
Fixed.
