### ISSUE TITLE
Multiple definitions of P_GEND_EVENTSETS

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#27]
I am getting multiple definitions of `P_GEND_EVENTSETS` in `program.c`. I can provide the P files.

**Comment by shazqadeer** [comment]
Could you please try to minimize the test and send me the P file?

**Comment by shazqadeer** [comment]
I have checked in a fix for the problem.  The event packing was busted for a program with more than 32 events.  I guess no test regression has more than 32 events :-).  I have checked in the fix but not re-run the regressions yet so you are unblocked pronto.  We should add a regression for more than 32 events.
