### ISSUE TITLE
Warning in the build process

### ISSUE THREAD

**Issue by desaiankush** [p-org/P#28]
@clovett @shazqadeer 
remove the warnings generated for labels when compiling the C code.

We could add this to the top of every generated program.c file:

#pragma warning (disable: 4101)

#pragma warning (disable: 4102)

And probably should put this at the bottom of every program.c file to restore back to default for the rest of your app:

#pragma warning (default: 4101)

#pragma warning (default: 4102)

**Comment by shazqadeer** [comment]
Fixed.
