### ISSUE TITLE
Wrong path in instructions of "Build P on Windows"

### ISSUE THREAD

**Issue by BusyJay** [p-org/P#283]
Wiki says:
>Add the following two lines to the Microsoft.PowerShell_profile normally found in D:\Users\<username>\Documents\WindowsPowerShell
>
>New-Item alias:pc -Value <P-Folder>\Bld\Drops\Release\Binaries\win-x64\Pc.exe
>function pmc { dotnet C:\Users\<username>\.nuget\packages\microsoft.coyote\1.0.4\lib\netcoreapp3.1\coyote.dll test $args}

But in fact path for pmc should be
> <P-Folder>/packages/microsoft.coyote/1.0.5/lib/netcoreapp3.1/coyote.dll

**Comment by ankushdesai** [comment]
Thanks a lot @BusyJay , I have fixed it. We are working on a language manual for P as well as a detailed tutorial. Please keep an eye out for it. Should be available by the end of this month.
