### ISSUE TITLE
Prt does not log unhandled event

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#29]
...because it calls the exception handler first and then returns. Also, is there a convenient way to log the exception type?

**Comment by shazqadeer** [comment]
What do you mean by the exception type?

**Comment by shazqadeer** [comment]
Here is a sample output from one regression test that leads to an unhandled event exception.

=================================
         Console output
=================================
OUT: <CreateLog> Machine Real1(1) is created
OUT: <StateLog> Machine Real1(1) entered state Real1_Init
OUT: <EnqueueLog> Enqueued event E1 with payload null on Machine Real1(1)
OUT: <DequeueLog> Dequeued event E1 with payload null by Machine Real1(1)
OUT: <ExitLog> Machine Real1(1) exiting state Real1_Init
OUT: <EnqueueLog> Enqueued event E2 with payload null on Machine Real1(1)
OUT: <StateLog> Machine Real1(1) entered state Real1_S1
OUT: <DequeueLog> Dequeued event E2 with payload null by Machine Real1(1)
OUT: <ExitLog> Machine Real1(1) exiting state Real1_S1
OUT: exiting with PRT_STATUS_EVENT_UNHANDLED
OUT:
EXIT: 1

It would be helpful if you explained how you would like the output changed and why?

**Comment by paulthomson** [comment]
Here is my output. I did not implement a good exception handler.

```
<CreateLog> Machine ArtifactManagerMachine(1) is created
<StateLog> Machine ArtifactManagerMachine(1) entered state Init
<EnqueueLog> Enqueued event ArtifactManagerInit with payload (< (0, 0, 0, 0), 0>, < (0, 0, 0, 0), 0>, < (0, 0, 0, 0), 0>, < (0, 0, 0, 0), 0>, < (0, 0, 0, 0), 0>) on Machine ArtifactManagerMachine(1)
<DequeueLog> Dequeued event ArtifactManagerInit with payload (< (0, 0, 0, 0), 0>, < (0, 0, 0, 0), 0>, < (0, 0, 0, 0), 0>, < (0, 0, 0, 0), 0>, < (0, 0, 0, 0), 0>) by Machine ArtifactManagerMachine(1)
<ExitLog> Machine ArtifactManagerMachine(1) exiting state Init
<StateLog> Machine ArtifactManagerMachine(1) entered state Initialize
<EnqueueLog> Enqueued event UpdateArtifactManager with payload ((false, false, 0, 0, false, false, false, 0, 0, false, 0, 0, 0, 0, 0, false, false, 0, 0, false, 0, false, false, 0), < (0, 0, 0, 0), 0>, [], []) on Machine ArtifactManagerMachine(1)
<DequeueLog> Dequeued event UpdateArtifactManager with payload ((false, false, 0, 0, false, false, false, 0, 0, false, 0, 0, 0, 0, 0, false, false, 0, 0, false, 0, false, false, 0), < (0, 0, 0, 0), 0>, [], []) by Machine ArtifactManagerMachine(1)
<ExitLog> Machine ArtifactManagerMachine(1) exiting state Initialize
Assertion failed: false && "Exception handler.", file d:\temp\pcrash\pmaster\src\prtdist\samples\nodeservicetest\nodeservicetest.cpp, line 98
```

Note that the unhandled event is not logged, but I think it would be logged if there was a state pushed. I will get things set up so I can make pull requests, as that will probably be easier.

**Comment by shazqadeer** [comment]
For a basis error handler that you could reuse, take a look at the file Tst\PrtTester\tester.c.

For your output, I would deduce that the unhandled event is UpdateArtifactManager since it was the last dequeued event by machine ArtifactManagerMachine(1) which is exiting with an unhandled event.
