### ISSUE TITLE
Link error in PrtDist samples

### ISSUE THREAD

**Issue by shazqadeer** [p-org/P#3]
After my recent fixes to deal with static functions, I am now getting a link error when I compile the generated C code using the solution files in the respective folders.

Error	51	error LNK2019: unresolved external symbol _PrtEnqueueWithInorder referenced in function _s_PrtDistSendEx	C:\Users\qadeer\Work\P\Src\PrtDist\Samples\TechFest2015-Demo\PrtDist.lib(PrtDist.obj)	FailureDetector

**Comment by desaiankush** [comment]
@shazqadeer. Fixed. Inconsistent function renaming.
