### ISSUE TITLE
Official vscode extension

### ISSUE THREAD

**Issue by BusyJay** [p-org/P#307]
I notice there are two P language extensions in vscode, https://marketplace.visualstudio.com/items?itemName=ankushdesai.p-language and https://marketplace.visualstudio.com/items?itemName=lovettchris.msr-vscode-p. Both of them are listed in developer accounts. So which one is *officially* supporting one?

I also found an outdated issue #157 that mentioned there was an extension in the source code, which seemed to be removed.

**Comment by lovettchris** [comment]
Oh, the lovettchris.msr-vscode-p is just a temporary place holder, I will see if I can delete it.

**Comment by lovettchris** [comment]
https://marketplace.visualstudio.com/items?itemName=lovettchris.msr-vscode-p is gone.  Thanks for pointing this out.
