### ISSUE TITLE
Include #line or line number comments in generated C code.

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#32]
Enhancement. It would be nice to have the P line numbers in the generated C code. If you use the [#line directive](https://msdn.microsoft.com/en-us/library/b5w2czay.aspx) then Visual Studio (or any other debugger) will jump directly to the appropriate line in the P file. You could even step through the P file. This would make seeing which assertion failed much easier.

**Comment by shazqadeer** [comment]
I have checked in a first cut of line numbers.

**Comment by paulthomson** [comment]
This is awesome!

**Comment by paulthomson** [comment]
I don't have permission to re-open this, but this is not quite working for me. The file paths are being interpreted by VS as relative paths. Removing `file:///` seems to fix it, weirdly.

**Comment by shazqadeer** [comment]
I have added /noSourceInfo option to control the emitting of source line information.
