### ISSUE TITLE
How can I generate C code?

### ISSUE THREAD

**Issue by roohitavaf** [p-org/P#325]
Hi, 

I just learned about P. I have a  couple questions. 

1- Can P be used to generate the actual code that we can use in production, or it can just be used for model checking like TLA+/PlusCal? 

2-I tried compiling the 2PC example, and it generated C# code. How can I generate C code? 

3- How can I efficiently use the output of the model checker. I get a very long text file containing the result, but it is very difficult to use this file. How do you usually use the ouptuts? Is there any other tools that help using the output in any way?

Thanks,
Mohammad

**Comment by ljackson** [comment]
I am trying to figure this out also.

This was my best guess so far:

`pc -outputDir:./CGenerated/ -generate:C PSrc/*.p PSpec/Monotonic.p PTst/*.p
----------------------------------------
----------------------------------------
Parsing ..
Type checking ...
Code generation ....
<Internal Error>:
 unrecognized type kind (Parameter 'type')
<Please report to the P team (p-devs@amazon.com) or create an issue on GitHub, Thanks!>
`

**Comment by ankushdesai** [comment]
Thanks for getting in touch.

Yes, P can generate C code. In the pproj file, update the target from CSharp to C.

@ShivKushwah, can you please point them to the cmake files you have to help build the generated C code from P.

We have used the generated C code to program enclaves as well as robotics systems.

**Comment by roohitavaf** [comment]
Thanks @ankushdesai 
Could you please also answer my third question? How do you usually use the output of the model checker? Do you have any special tool for reading it?

**Comment by roohitavaf** [comment]
I get parsing error when I change `CSharp` to `C`:

```
PS C:\Users\Mo\Projects\P\Tutorial\TwoPhaseCommit> pc -proj:TwoPhaseCommit.pproj
----------------------------------------
==== Loading project file: TwoPhaseCommit.pproj
....... includes p file: C:\Users\Mo\Projects\P\Tutorial\TwoPhaseCommit\PSrc\Client.p
....... includes p file: C:\Users\Mo\Projects\P\Tutorial\TwoPhaseCommit\PSrc\Coordinator.p
....... includes p file: C:\Users\Mo\Projects\P\Tutorial\TwoPhaseCommit\PSrc\Participant.p
....... includes p file: C:\Users\Mo\Projects\P\Tutorial\TwoPhaseCommit\PSrc\Timer.p      
....... includes p file: C:\Users\Mo\Projects\P\Tutorial\TwoPhaseCommit\PSpec\Atomicity.p 
....... includes p file: C:\Users\Mo\Projects\P\Tutorial\TwoPhaseCommit\PTst\TestDriver.p 
....... includes p file: C:\Users\Mo\Projects\P\Tutorial\TwoPhaseCommit\PTst\TestScripts.p
<Error parsing project file>:
 Expected true or false, received 
------------------------------------------
Recommended usage:

>> pc -proj:<.pproj file>

------------------------------------------
Optional usage:

>> pc file1.p [file2.p ...] [-t:tfile] [options]
    -t:[target project name]   -- project name (as well as the generated file)
                                  if not supplied, use file1
    -outputDir:[path]          -- where to write the generated files
    -aspectOutputDir:[path]    -- where to write the generated aspectj files
                                  if not supplied, use outputDir
    -generate:[C,CSharp,RVM]   -- select a target language to generate
        C       : generate C code
        CSharp  : generate C# code 
        RVM     : generate Monitor code
    -h, -help, --help          -- display this help
```

**Comment by nhardt** [comment]
I'm hitting this issue as well. Based on https://github.com/p-org/P/blob/88d395aaefcafa94f13f3751819e0337df443bc1/Src/PCompiler/CommandLine/ParseCommandlineOptions.cs#L327 I tried adding `sourcemaps="true"` or `sourcemaps="false"` to the .pproj file. It got further but failed here:

```
----------------------------------------
==== Loading project file: TwoPhaseCommit.pproj
//snip
----------------------------------------
----------------------------------------
Parsing ..
Type checking ...
Code generation ....
<Internal Error>:
 unrecognized type kind (Parameter 'type')
<Please report to the P team (p-devs@amazon.com) or create an issue on GitHub, Thanks!>
   at Plang.Compiler.Backend.C.CNameManager.SimplifiedRep(PLanguageType type) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/C/CNameManager.cs:line 166
   at Plang.Compiler.Backend.C.CNameManager.GetNameForType(PLanguageType type) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/C/CNameManager.cs:line 88
   at Plang.Compiler.Backend.C.PrtCodeGeneratorImpl.WriteSourceDecl(TextWriter output, IPDecl decl) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/C/CCodeGenerator.cs:line 294
   at Plang.Compiler.Backend.C.PrtCodeGeneratorImpl.GenerateSourceFile(Scope globalScope) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/C/CCodeGenerator.cs:line 72
   at Plang.Compiler.Backend.C.PrtCodeGeneratorImpl.GenerateCode(ICompilationJob job, Scope globalScope) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/C/CCodeGenerator.cs:line 43
   at Plang.Compiler.Backend.C.CCodeGenerator.GenerateCode(ICompilationJob job, Scope globalScope) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/C/CCodeGenerator.cs:line 22
   at Plang.Compiler.Compiler.Compile(ICompilationJob job) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Compiler.cs:line 38
   at Plang.Compiler.CommandLine.Main(String[] args) in /home/runner/work/P/P/Src/PCompiler/CommandLine/CommandLine.cs:line 25
```

This is my only change: 
```
-<Target>CSharp</Target>
+<Target sourcemaps="false">C</Target>
```

"true" and "false" produced the same result.

**Comment by pinzaghi** [comment]
I'm having this same issue trying to generate C code.

**Comment by ankushdesai** [comment]
The tutorial for generating C code will be made available soon, its under development right now. 

You can look at the repo: https://github.com/Drona-Org/Drona
