### ISSUE TITLE
Missing P_GEND_TYPE_[TypeName]

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#33]
I was previously getting definitions like the following in `program.c`:

```
PRT_TYPE *P_GEND_TYPE_ARTIFACTType = &P_GEND_TYPE_215;
```

Thus I can refer to the types from the C code easily (by name). I then added another foreign type and these have all disappeared. I am trying to create a test case but I can't get these definitions to appear. I can send you files privately or maybe you can tell what the problem is.

**Comment by paulthomson** [comment]
Perhaps more importantly: the declarations for the types are still generated in `program.h` so now I can't link! 

```
error LNK2001: unresolved external symbol P_GEND_TYPE_ARTIFACT_ASSEMBLY_Type
```

**Comment by paulthomson** [comment]
Test case:

Compile with `pc` and see that the definitions (e.g. `P_GEND_TYPE_MyOtherType`) are missing from `program.c`. Comment out the `StringBuffer` type and compile again to see that the definitions are now present in `program.c`. 

```
type StringBufferType;

type MyType = 
(
	a : int,
	b : int
);

type MyOtherType = 
(
	a : MyType,
	d : int
);


main machine MyMachine
{
    // Fields: 

    var FieldV : MyType;

    // States: 

    start state Init
    {
        entry
        {
            
        }
    }

}
```

**Comment by shazqadeer** [comment]
Fixed.
