### ISSUE TITLE
P2P communication

### ISSUE THREAD

**Issue by pinzaghi** [p-org/P#341]
Hello,

I'm trying to model a protocol where every node knows every other node. When I create instances of this Node() I cannot pass by argument the list of peers because I'm creating them at that moment. In this protocol, every node may broadcast to all nodes.

How do I solve this? Should I add a special configuration state to receive the event with the sequence of peers after the Init?

**Comment by ankushdesai** [comment]
Yes, you are right. One way to model this kind of scenarios is to wait for the configuration event in the start state of the state machine. The configuration event has the set of all machines in its payload.

**Comment by pinzaghi** [comment]
Thank you.
