### ISSUE TITLE
Build currently fails

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#35]
Running `build.bat release x64` (and probably all other combinations) currently fails when trying to build the P samples. I think this is because `pc` no longer outputs `program.c` and `program.h`.

* The `p.targets` file will need to be changed.
* The P sample projects will need to be changed to include different files. Also, if I switch to x64 in VS2015, then some of the P sample projects are still Win32, so this could also be fixed.  
* `.gitignore` will probably need to be updated.

**Comment by shazqadeer** [comment]
Thanks to Chris, the  build appears to be fixed now.  

@clovett : Is the second bullet in Paul's original post still a problem?
