### ISSUE TITLE
PTst for SimplePaxos missing

### ISSUE THREAD

**Issue by wutka** [p-org/P#358]
The SimplePaxos tutorial is missing the Ptst folder even though it is mentioned in the .pproj. I wasn't sure if it was just forgotten in the commit or if that tutorial hasn't been completed yet.

**Comment by ankushdesai** [comment]
Hi @wutka, yes, I will update the example soon. its currently incomplete. It will be added along with the detailed documentation.

**Comment by ankushdesai** [comment]
Removed SimplePaxos from the tutorials.
