### ISSUE TITLE
No UserMkFreshForeignValue

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#36]
I am trying to run one of my test cases as a C program to debug a potential issue with the C runtime. However, it seems that when P code asks for a fresh foreign value, the runtime just returns `1`, `2`, `3`, etc. My `User*Foreign*` functions assume these values are pointers and there is no way to distinguish these fake values from real pointers (in theory). So, my program will (almost certainly) crash. 

It would be useful to either have a `UserMkFreshForeignValue` function (which could optionally replace the default). Or, a parameter could be added to most of the `User*Foreign*` functions so that my code can distinguish between a "fresh" foreign value and a real foreign value. (I'd personally prefer the former.)

**Comment by shazqadeer** [comment]
An informal expectation from the programmer is that all uses of fresh(T) occur in model code (model machines or model functions).  In  that case, one of two things will happen.  Either models are erased (by default) and all foreign values come from foreign code.  Or models are not erased (/doNotErase option to the compiler) and all foreign values come from P runtime. In either case, I don't see any possibility for confusion.

**Comment by paulthomson** [comment]
I guess there are two questions:
1. Is `fresh` ever expected to be used in C code?
2. If yes, then is there any way that such fresh foreign values can be used when the "real" type of the foreign values is pointers? (And do we care?)

Regarding (1), my argument for allowing fresh in C code is mainly for the ability to execute tests as C code for debugging (i.e. the ability to step through the code) and comparing the zinger runtime with the C runtime (and to potentially find issues with either). Since `/doNotErase` exists, I assume this also suggests the answer is yes. 

Regarding (2), I think the answer is currently no. Thus, if you write P code that has pointers as foreign values, then `fresh` cannot be used (in theory) with the C runtime. Thus, you cannot run such test cases on the C runtime for debugging. 

A workaround is to assume that "small" foreign values are not actually pointers and to write additional code in your "foreign function handlers" to handle this case. This relies on undefined (but fairly reliable) behavior. This additional code could also hide errors if you accidentally introduce an invalid pointer value that happens to be "small". Another possibility is to make it so the `fresh` C implementation is a (private?) function pointer, so that it can be changed for testing purposes.

**Comment by shazqadeer** [comment]
I am still not following the point you are raising.  You will compile either with or without the /doNotErase option. Here is what will happen:
1. You use /doNotErase option.  In this case, the actual foreign code will not be used at all.  fresh will compile to Prt runtime fresh API that just uses increasing natural numbers.  Since the real foreign code is not even linked, there is no problem.

2. You do not use /doNotErase option.  In this case, the actual foreign code is linked.  Since all occurrences of fresh are in model code, they will all be erased.  Now you will consistently go through foreign code.

**Comment by paulthomson** [comment]
I see now. I need to change my C code so that it does not call `PrtUpdateForeignFn`, then my model code will work fine.
