### ISSUE TITLE
[Prt] Machine state becomes garbage value

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#37]
When compiling a test case to C, I get a `read access violation`. I believe the `currentState` field of `PRT_MACHINEINST_PRIV` is a garbage value, but I could be wrong. It could be a bug in Prt or in the generated code. I am not sure how to debug this. Can Visual Studio do reverse debugging? :smile:

**Comment by paulthomson** [comment]
`PrtExecution.c` line 817. The `transIndex` is out of bounds. Not sure why. Could add a bounds check here: `PRT_DBG_ASSERT(transIndex < nTransitions, "Check Failed");`

**Comment by shazqadeer** [comment]
Closing this issue.  We determined that the bug is due to incorrect packed event set translation.
