### ISSUE TITLE
Type errors still sometimes hang the compiler

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#39]
I just changed a few `int` types to be foreign types and now the compiler hangs. I think we already know about this issue, but I am creating this so we don't forget about it.

**Comment by desaiankush** [comment]
Closing. The foreign type implementation has been updated.

**Comment by shazqadeer** [comment]
The issue with typing errors hanging the compiler is not really resolved.  It is not really an issue with foreign types.  So, the description of this particular issue is misleading.  I will create a fresh issue.
