### ISSUE TITLE
Confused on the purpose of P

### ISSUE THREAD

**Issue by Pyrolistical** [p-org/P#396]
I don't get it. The required [send semantics](https://p-org.github.io/P/advanced/psemantics/) requires send to be reliable. AKA consensus among the nodes.

Consensus is the hardest part of correctness with distributed systems.

A state machine running on top of a consensus algorithm, like [raft](https://raft.github.io/), doesn't need to know its a distributed system any more. The state machine can act as if its on a single machine now.

Given that, then what does P have to do with distributed systems? Sure it helps you build state machines better by exploring the error space and all that, but where is the distributed system part?

**Comment by ankushdesai** [comment]
Hi @Pyrolistical, thanks for your question. Can you please explain how reliable send between two nodes is a consensus all nodes? May be I am missing something that you are assuming?

**Comment by Pyrolistical** [comment]
By requiring a reliable send, you've defeated the one of the biggest problems with distributed systems. IE. You not longer have a distributed system problem.

This is why I am confused. P keeps saying its a programming language to build distributed systems, but the fact it requires a solution that trivializes distributed system makes me question if P is about building distributed systems. In fact from what I can tell P is more about building state machines.

**Comment by pinzaghi** [comment]
You can model non-reliable communication using the non-deterministic choice $, see this tutorial: https://p-org.github.io/P/tutorial/common/
