### ISSUE TITLE
Prefix error messages (optionally?) with `relativePath:lineNo(:colNumber)?`

### ISSUE THREAD

**Issue by nicolagi** [p-org/P#399]
Compiler output could be made more useful if error messages used the format `relativePath:lineNo(:colNumber)?` for file locations, as is the convention in most Linux tools. Existing scripts can then be re-used. For example, where the current output is,

```
[Server.p] parse error: line 21:6 missing '(' at 'r'
```

I think it'd be useful to have

```
PSrc/Server.p:21:6: missing '(' at 'r'
```

If you don't want to change this (or provide it as an optional format) you could consider at least printing the relative path to the file, rather than just the name.

The format I'm requesting is widely supported in terminals and editors.

**Comment by ankushdesai** [comment]
Thanks @nicolagi, I completely agree with you that the proposed change would be helpful for the users. 
We will work on it and get it out soon.

**Comment by ankushdesai** [comment]
@nicolagi this has been updated in the latest version 1.1.5. Please let me know what you think.
