### ISSUE TITLE
inconsistent parameter list of foreign functions in PrtDist samples

### ISSUE THREAD

**Issue by shazqadeer** [p-org/P#4]
The following warning is worrisome:

Warning	29	warning C4030: first formal parameter list longer than the second list	c:\users\qadeer\work\p\src\prtdist\samples\pingpong\program.h	136	1	PingPong

The signatures of generated C code for P functions changed. The foreign functions provided by PrtDist need to reflect that change.

**Comment by desaiankush** [comment]
Fixed.
