### ISSUE TITLE
Implement copy propagation optimisation pass?

### ISSUE THREAD

**Issue by dijkstracula** [p-org/P#437]
In the following event handler (part of the ClientServer tutorial),

```
103     on eWithDrawResp do (resp: tWithDrawResp) {
104       assert resp.rId in pendingWDReqs,
105         format ("unexpected rId: {0} received, expected one of {1}", resp.rId, pendingWDReqs);
106       pendingWDReqs -= (resp.rId);
107    ...
```

The following backend code is generated:

```
            TMP_tmp0_3 = ((Integer)resp_1.get("rId"));
            TMP_tmp1_2 = pendingWDReqs.contains(TMP_tmp0_3);
            TMP_tmp2_2 = ((Integer)resp_1.get("rId"));
            TMP_tmp3_2 = (HashSet<Integer>)Values.clone(pendingWDReqs);
            TMP_tmp4_2 = MessageFormat.format("unexpected rId: {0} received, expected one of {1}", TMP_tmp2_2, TMP_tmp3_2);
            tryAssert(TMP_tmp1_2, TMP_tmp4_2);
            TMP_tmp5_2 = ((Integer)resp_1.get("rId"));
            pendingWDReqs.remove(TMP_tmp5_2);
```

Of course, `TMP_tmp0_3`, `TMP_tmp2_2`, and `TMP_tmp5_2` are all redundant accesses.  I wonder how feasible it would be to implement copy propagation or common subexpression elimination as an IR transformer?

**Comment by ankushdesai** [comment]
Good point! I have always been scared of adding any optimization into the compiler until really needed. Performance has never been a concern for the generated code so far (not any more as we start using P generated code outside testing).

But correctness would need to be thoroughly tested if we add optimizations.

Do you have a plan or design?

**Comment by dijkstracula** [comment]
Yep, strong agree that adding an optimisation that breaks the compiler would be a _bad idea_!

I also wonder whether the CLR and JVM's JITs (or even `javac`) are smart enough to elide those redundant accesses; running a quick experiment there might be the first thing to try before we try anything fancy on our end.

But, given that the IR is already in SSA, I think there are straightforward procedures for doing this?  Let me investigate and come up with a concrete proposal if they're not elided at runtime.

**Comment by ankushdesai** [comment]
This is so cool! thanks for the study @dijkstracula, love it!

**Comment by ankushdesai** [comment]
Are there similar optimization flags that we can use for C# compiler as well?

**Comment by dijkstracula** [comment]
Couldn't say for sure, but [this](https://instil.co/blog/simd-performance-with-csharp-and-cpp/) suggests that you can so long as you're using non-VS Code Visual Studio.  [This](https://stackoverflow.com/questions/66843703/does-jetbrains-rider-have-function-like-view-disassembly-code-in-the-visual-stud) suggests such functionality isn't present in Rider.
