### ISSUE TITLE
GCC compile issue with #include "PrtWinUser.h"

### ISSUE THREAD

**Issue by clovett** [p-org/P#45]
I'm getting p-runtime to compile on Nuttx and "PrtWinUser.h" in the generated P code seems too windows specific.  Can we genericize that or add option to generate other OS platforms, in my case I want PrtNuttxUser.h... unless you can generalize that - for example, call it "PrtUser.h" and use #ifdef <PLATFORM> inside that header for any platform specifics...

**Comment by shazqadeer** [comment]
Does the recent checkin by Ankush fix this problem?

**Comment by lovettchris** [comment]
Yep.

**Comment by shazqadeer** [comment]
Excellent.  Thanks, Ankush.
