### ISSUE TITLE
[Java] extract source files in a multi-file project-like structure

### ISSUE THREAD

**Issue by dijkstracula** [p-org/P#454]
We started discussing this [here](https://github.com/p-org/P/pull/453): currently we extract all Java code into a single `.java` file, wrapped in a [top-level static class](https://github.com/dijkstracula/prtsandbox/blob/main/src/main/java/tutorialmonitors/ClientServer.java#L14) that acts as a namespace because of Java's "one file = one class" rule.  With FFI we are now entering the world of having multiple files and need to generate POMs anyway, so @ankushdesai proposed:

> Would it be too hard to go down one [source] file per machine name? and put all events into Events and types into Types, all global FFI into globalFFi. How hard would that be?

Here's one possible way that the above could look in terms of a package structure (just putting this here for illustrative purposes and not advocating for precisely this, necessarily):

```
+---somePProj
    +---pom.xml
    +---machines
        +---someMonitor.java 
        +---anotherMonitor.java
        +---yetAnotherMonitor.java
    +---events
        +---DefaultEvent.java
        +---PHalt.java
        +---eReadReq.java
        +---eReadResp.java
    +---types
        +---PTuple_reqID.java
        +---PTuple_reqID_status_value.java
        +---tWithDrawRespStatus.java    
    +---ffi
        +---Global.java
        +---someMonitor.java
```

My reply was that I don't think it's too terribly hard but we should first figure out what problem doing this would solve and whom it would help, so we know whether to build it and can evaluate whether we designed and built it in the right way.  

One thing that _is_ nice about the above is that we could potentially generate FFI stubs that developers intend on filling in: so, if `someMonitor` relies on some foreign functions (but not the other monitors), we can stub those FFI bindings out at generation time and have developers fill them in, and if they are filled in then we won't overwrite them with stubs again.  I don't know whether that aligns with developers' workflows, though - it feels nice to me, but would they like it?

**Comment by ankushdesai** [comment]
One biggest benefit of this is clean looking code :). Can something beat that! 
Also, I think what you said would work, the good part about this is then developer knows they only need to worry about the ffi folder.

**Comment by dijkstracula** [comment]
After https://github.com/p-org/P/pull/460 this was done.
