### ISSUE TITLE
GCC v4.8 compile issue with generated struct initializers

### ISSUE THREAD

**Issue by clovett** [p-org/P#46]
The initializer for the "union" part of the PRT_TYPE and PRT_VALUE structs in the generated code need to be surrounded by another level of curly braces, for example, this:

```
  PRT_TYPE P_GEND_TYPE_0 = 
  {
    PRT_KIND_ANY,
    NULL
  };
```

needs to be this:

```
  PRT_TYPE P_GEND_TYPE_0 = 
  {
    PRT_KIND_ANY,
    { NULL }
  };
```

**Comment by shazqadeer** [comment]
Fortunately, cl.exe does not complain when I added the braces.  So, I added the braces unconditionally.
