### ISSUE TITLE
GCC compile errors with unused variables, and undeclared functions

### ISSUE THREAD

**Issue by clovett** [p-org/P#47]
I'm getting p-runtime to compile on nuttx using GCC and the generated P output contains functions with missing prototypes, and unused variables and unused goto labels.  These errors can be avoided by turning off the following compiler features, but I'd prefer not to have to do that because these features are handy way to keep my code clean:

		-Wno-missing-prototypes
		-Wno-missing-declarations
		-Wno-unused-but-set-variable
		-Wno-unused-variable
		-Wno-unused-label

**Comment by shazqadeer** [comment]
I have made an attempt to eliminate unused variables.  However, it is unlikely I have succeeded in eliminating the need for all of the above options.  Please do a pull and try it out and provide P file as repro for each specific problem you still face.

**Comment by lovettchris** [comment]
Ok, you can close this issue, I will file separate issues for anything else I find in this area.

**Comment by shazqadeer** [comment]
ok.
