### ISSUE TITLE
Per-target subdirectories

### ISSUE THREAD

**Issue by dijkstracula** [p-org/P#471]
A suggestion from Jigar: with P projects where more than one target might be used, it might make sense to extract e.g. all generated C# files into `PGenerated/dotnet`, all generated Java files into `PGenerated/java`, and so on.  Similarly, foreign function implementations could have a similar structure (i.e. `PForeign/dotnet/MyMagicalClass.cs` and `PForeign/java/MyMagicalClass.java`, etc)

**Comment by ankushdesai** [comment]
I support this change, I agree, it would be helpful.

**Comment by dijkstracula** [comment]
Unassigning this from me since I won't get to it before my internship ends.

**Comment by ankushdesai** [comment]
We have not come across a case where a team using multiple backends. Closing this issue for now and will re-open if needed.
