### ISSUE TITLE
Specs appear to not validate that only observed events are handled

### ISSUE THREAD

**Issue by dijkstracula** [p-org/P#474]
The Java backend only emits events that are actually used in monitors - in particular, if an event never appears in an `observes` clause, then a class definition is not generated for it.

Consider the following program:

```
nathta@bcd0741cf59d /tmp % cat -n foo.p
     1  event addEvent: (i: int, total: int);
     2  event mulEvent: (i: int, total: int);
     3
     4  spec RingSpec observes addEvent {
     5    start state Init {
     6      on mulEvent do {
     7        print "We'll never get here!";
     8      }
     9    }
    10  }
    11
    12  machine Driver {
    13    start state Init {}
    14  }
    15
    16  test doIt [main=Driver]: {Driver};
    17
nathta@bcd0741cf59d /tmp %
```

This compiles cleanly, perhaps unexpectedly, extracting to dotnet:

```
nathta@bcd0741cf59d /tmp % pcl -generate:CSharp foo.p
...
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.88
nathta@bcd0741cf59d /tmp %
```

However, it dies during Java extraction, as no definition is emitted for `MulEvent` but an event handler is defined for it:

```
nathta@bcd0741cf59d /tmp % pcl -generate:Java foo.p
...
[ERROR] /private/tmp/PMachines.java:[23,35] cannot find symbol
[ERROR]   symbol:   class mulEvent
[ERROR]   location: class PGenerated.PEvents
...
nathta@bcd0741cf59d /tmp %
```

This is surprising; I expected both to fail but at the frontend stage, with an error to the effect of `MulEvent not present in the Observes list` or some such thing.

We need to either make the Java event pruning code smarter (by walking all event handlers in machines and not relying on the `observes` clause?), more conservative about pruning generated events or more permissive about pruning event handlers with payloads that don't appear in `observes`, or report this P program as invalid in all cases.

**Comment by dijkstracula** [comment]
Thinking about this more: there are seemingly two problems with the above example program: not only are we trying to handle an event we have not indicated that we're observing, but we're also failing to mark an event we _have_ indicated that we're observing as one we are ignoring?

**Comment by ankushdesai** [comment]
This is going to be a bit tricky and would be good to figure out the right solution.
The reason we dont have a check like that in P right now is because we can have a code like the following:

```
state S {

 entry {
 .. 
 raise E;
 }

 on E do {}
}
```

Need to think about whats the cleanest solution ....

**Comment by ankushdesai** [comment]
I am more leaning towards: (1) not allows raise inside monitors (2) then add the restriction that all events on the event handlers must be in the observes set.
