### ISSUE TITLE
whitespace normalization

### ISSUE THREAD

**Issue by lovettchris** [p-org/P#50]
Let's do a big scrub across the code base to normalize newlines and replace tab characters with spaces so we stop getting "diff's" that show more changes than were actually made.  This needs to be planned at a time when folks don't have big changes they need to merge...

**Comment by desaiankush** [comment]
I dont have any uncommitted changes in the main branch. 
Do we have to do this in all the branches ?

**Comment by lovettchris** [comment]
Once done you might want to pull it into your branch before making big changes…

**Comment by lovettchris** [comment]
But if that is not practical and you have big changes in your branch that you cannot push up to the master branch then we may need to come up with a different plan…something more incremental perhaps…

From: Chris Lovett
Sent: Wednesday, May 4, 2016 1:52 PM
To: 'p-org/P' <reply@reply.github.com>; p-org/P <P@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [p-org/P] whitespace normalization (#50)

Once done you might want to pull it into your branch before making big changes…

**Comment by shazqadeer** [comment]
I am worried that if it is not done across all branches then when a merge from a branch back to main happens, we will be back in the same soup that we are in now.

**Comment by lovettchris** [comment]
Right, but if you do it in all branches you will still have a merge problem because it will think that is a conflicting edit I think.  We may need to do a test run on a single file and see what happens…

**Comment by lovettchris** [comment]
Ok, I removed TAB chars from Prt.h, can you do the same in your branch then try and merge my change into your branch and see what happens ?

See change https://github.com/p-org/P/commit/4da6fd0d9ce40328b573d2b4455e53c757e3c0e6

PS: I used “Select all” + “Edit -> Advanced -> Untabbify Selected Lines”.

From: Chris Lovett
Sent: Wednesday, May 4, 2016 2:03 PM
To: 'p-org/P' <reply@reply.github.com>; p-org/P <P@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [p-org/P] whitespace normalization (#50)

Right, but if you do it in all branches you will still have a merge problem because it will think that is a conflicting edit I think.  We may need to do a test run on a single file and see what happens…

**Comment by paulthomson** [comment]
It looks like there is an option to ignore whitespace changes when merging:
http://stackoverflow.com/questions/5256769/git-merge-and-fixing-mixed-spaces-and-tabs-with-two-branches

I have no experience with it though.

**Comment by desaiankush** [comment]
Hi Chris,
Can you do this change on the entire main branch.
I will take care of the merging part for my modp branch.
Please let me know when you done with this change as I would like to branch
out after that.

Regards
Ankush

**Comment by lovettchris** [comment]
Ok, I will coordinate with Shaz and get this done.
