### ISSUE TITLE
.net core 3.1 required

### ISSUE THREAD

**Issue by kstatz12** [p-org/P#503]
Is it required to have the 3.1 sdk installed if we already have the .net 6 sdk? im getting 

```pc
You must install .NET to run this application.

App: /home/karl/.dotnet/tools/pc
Architecture: x64
App host version: 6.0.9
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=ubuntu.22.04-x64&apphost_version=6.0.9
```

**Comment by ankushdesai** [comment]
Hi @kstatz12, you are right the current version of P requires .Net 3.1.
We are working on a release of P 2.0 which will move P to .Net 6.0 and also improve the installation process as a single step.

We will release the new version in 2 weeks. Please stay tuned :)

**Comment by kstatz12** [comment]
> We are working on a release of P 2.0 which will move P to .Net 6.0 and also improve the installation process as a single step.

Awesome! super exciting. Great work
