### ISSUE TITLE
[Tst] Tests with deprecated push statement

### ISSUE THREAD

**Issue by aman-goel** [p-org/P#509]
Hi @ankushdesai,

Several regression tests in [Tst/RegressionTests](https://github.com/p-org/P/tree/master/Tst/RegressionTests) have push statement. Since push statement is now deprecated, P compiler throws a StaticError for these examples.

During regression testing, these examples (like [Integration/DynamicError/Actions_5/Actions_5.p](https://github.com/p-org/P/blob/master/Tst/RegressionTests/Integration/DynamicError/Actions_5/Actions_5.p)) should throw a StaticError due to compilation failure. However, these are currently listed in DynamicError or Correct paths, and somehow current regression testing for C# doesn't catch them as unexpected.

I see two options: a) either update these examples to not use push statement, or b) move these examples to appropriate StaticError directory.
Also, we need to correct C# regression testing harness on why it is unable to catch them as StaticError.

Here is the complete list of these examples in [Tst/RegressionTests](https://github.com/p-org/P/tree/master/Tst/RegressionTests):
(derived by running ``grep -l -r 'on.*push' | grep -v "StaticError"``)

````
./Integration/DynamicError/Multi_Paxos_4/Multi_Paxos_4.p
./Integration/DynamicError/Actions_6/Actions_6.p
./Integration/DynamicError/Multi_Paxos_3/Multi_Paxos_3.p
./Integration/DynamicError/SEM_OneMachine_16/ExplicitPopExit.p
./Integration/DynamicError/SEM_OneMachine_11/PushImplicitPopWithSend.p
./Integration/DynamicError/SEM_OneMachine_20/BugReproIdenticalTerms.p
./Integration/DynamicError/SEM_OneMachine_21/BugReproIdenticalTerms_workaround.p
./Integration/DynamicError/SEM_OneMachine_10/Push.p
./Integration/DynamicError/SEM_OneMachine_32/RaisedHaltHandled.p
./Integration/DynamicError/SEM_OneMachine_9/PushItself.p
./Integration/DynamicError/Actions_5/Actions_5.p
./Integration/DynamicError/SEM_OneMachine_12/PushExplicitPop.p
./Integration/DynamicError/SEM_OneMachine_15/ImplicitPopExit.p
./Integration/DynamicError/SEM_OneMachine_41/NullHandlerInLoop.p
./Integration/DynamicError/SEM_OneMachine_13/PushTransInheritance.p
./Integration/DynamicError/SEM_OneMachine_38/NullHandlerInheritedByPushTr.p
./Integration/DynamicError/SEM_OneMachine_39/TopNullHandlerOverridesInherited.p
./Integration/DynamicError/PingPongWithCall/PingPongWithCall.p
./Feature4DataTypes/DynamicError/CastInExprs2/CastInExprsDynError.p
./Feature4DataTypes/DynamicError/CastInExprs5/CastInExprsdynError.p
./Feature4DataTypes/DynamicError/CastInExprs4/CastInExprsDynError.p
./Feature4DataTypes/DynamicError/CastInExprs3/CastInExprsDynError.p
./Feature4DataTypes/DynamicError/CastInExprs6/CastInExprsDynError.p
./Feature4DataTypes/DynamicError/CastInExprs1/CastInExprsDynError.p
./Feature5ModuleSystem/Correct/ElevatorMod/Elevator.p
./Feature5ModuleSystem/Correct/OSR/OSRDriver.p
./Feature5ModuleSystem/Correct/Elevator/Elevator.p
````

--
Aman
@aman-goel

**Comment by ankushdesai** [comment]
@aman-goel thanks Aman for bring this to attention. Its a bit alarming that I missed this.
Having another checker in the mix will help us catch bugs and do some fancy differential testing, lol, fancy term.

If at all you get time, can you help debug, why the unit tests are missing this. I think this has something to do with the error code returned by the commandline.
