### ISSUE TITLE
Static error is not detected when the same event is used in goto transition and in "defer"

### ISSUE THREAD

**Issue by ellab123** [p-org/P#51]
[EventDeferredTransDoSameState.txt](https://github.com/p-org/P/files/251377/EventDeferredTransDoSameState.txt)
Static Error is not detected if the same event is used in “goto” and deferred
-	see attached test, lines 24-25 (change file extension from .txt to .p before compiling).
Note that two other combinations of duplicate events are detected as static errors: 
- same event is used in “goto” and “do”
- same event is used in “do” and deferred
These combinations are also present in the attached test (commented out).

**Comment by desaiankush** [comment]
Hi Ella,
I dont think this is a problem as far as I remember. Not sure if the semantics have changed after that.
Defer is considered as an action handler and hence
       //defer PONG;
	//on PONG do Action1;
is like defining multiple action handlers for the same event and is considered as an error.

        on SUCCESS goto WaitPong;  
	defer SUCCESS;

This is fine because one is an action handler and the other is a transition. Transition has higher precedence over action handler, we should add a test case to assert this.

**Comment by ellab123** [comment]
Hi, Ankush,
Just to be sure I understand: are you saying that the attached test is compiled correctly and there should be no static error?

**Comment by shazqadeer** [comment]
I think Ankush is right about his recollection of the design.  But I am now wondering if the design should be changed to meet Ella's expectations.  It is just confusing to allow more than one "action" for an event in a state.

**Comment by shazqadeer** [comment]
Sorry, closed by mistake.

**Comment by desaiankush** [comment]
This design decision was made to be consistent. For example, because of push-transitions there is a possibility that actions and transitions may be defined for an event in a state (inherited actions). In that case, transition gets higher priority over actions.

**Comment by shazqadeer** [comment]
I think that the behavior should be as follows:
1. Error if some common event in "goto",  "push", or "do"
2. No error if same event in "deferred" and "goto"
3. No error is same event in "deferred" and "push"
4. No error if same event in "deferred" and "do"

Using the approach above, we do not lose any generality and it is less confusing to the programmer.  The reason for allowing an event to appear in both "deferred" and one of the other categories is that the "deferred" annotation is applicable only to dequeued events and not to raised events.  It is possible that the programmer wants to do something only when an event e is raised but does not want to dequeue e in some state.

**Comment by shazqadeer** [comment]
On second thought, I think it is nicer and less confusing to disallow event duplication.  I have fixed the type checker.
