### ISSUE TITLE
VSCode extension syntax highlighting not working

### ISSUE THREAD

**Issue by henryliu5** [p-org/P#529]
Hi, I have been using IntelliJ as my IDE for P and the syntax highlighting works great after setup, but wanted to switch to VSCode for other reasons.

I installed the VSCode extension for syntax highlighting from [here](https://marketplace.visualstudio.com/items?itemName=ankushdesai.p-language) but I am not sure if it is working correctly. It looks like the sample image on the page for the "ping pong" sample doesn't load, so I'm exactly sure what the expected behavior should be.

This is what my editor looks like on the Client.p file from the client server tutorial:
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/19509472/203855352-b7b66ed5-928a-4820-9193-c8f529213abf.png">

Is there an issue with the extension/something I have not done correctly? Is this what the syntax highlighting should look like?

**Comment by ankushdesai** [comment]
Hey! We dont currently support the VSCode extension and its not being updated for a while.

**Comment by oberstet** [comment]
yeah:( also, the intellij thing isn't working either (tried the zip) for me:

![grafik](https://user-images.githubusercontent.com/233340/211816638-43519b06-e222-481b-8d5c-e654db8f88a1.png)

this is on the latest intellij community tarball on ubuntu 22. is the syntax highlighting in intellij supported on vscode?

**Comment by ankushdesai** [comment]
We now have a VSCode extension for P called Peasy: https://p-org.github.io/peasy-ide-vscode/
