### ISSUE TITLE
Installation instructions should say you need nuget as a dotnet source

### ISSUE THREAD

**Issue by hwayne** [p-org/P#544]
If you don't do that, you get an error like

> error NU1101: Unable to find package p. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages

or

> error NU1100: Unable to resolve 'p (>= 0.0.0)' for 'net6.0/any'.

When I investigated it turns out I didn't have the Nuget site as a source. I added it based on the instructions [here](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-add-source) and it worked.

You can test you have the appropriate source with

```
dotnet nuget list source
Registered Sources:
   nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
```

**Comment by ankushdesai** [comment]
Thanks, we will get this fixed in the new release and add it to the documentation.
