### ISSUE TITLE
Add numeric operators on foreign types

### ISSUE THREAD

**Issue by clovett** [p-org/P#57]
It would be nice if our foreign "float" types could be used more naturally in the P programming language.  For example, if I could write this:

var x : float32;
var y : float32;
x = 10;
y = 10 / 3;

This could be done if you had a standard way of naming foreign operator stubs which you map this division operation to, for example, the name in this case might be: P_FUN_OperatorDivideFloat32Float32 and the stub might be:

PRT_VALUE _OperatorDivideFloat32Float32 (PRT_VALUE_ a, PRT_VALUE\* b);

Similarly for "cast", "add", "subtract", "multiply".  Then you could also get into automatic casting of numeric types (if you knew float32 was numeric you could assume a stub provides cast to int and back, then you could also deal with mixed types in arithmetic expressions.

**Comment by shazqadeer** [comment]
@clovett : Are you proposing something specific to float32/64 or a general mechanism for foreign types?

**Comment by clovett** [comment]
Ideally something generalizable for any numeric type.

**Comment by shazqadeer** [comment]
We have decided to add a float type natively to P.  For .NET, float will compile to double.  For native, float will compile to either float for 32-bit compilation and double for 64-bit compilation.  I will take responsibility for implementing float.

**Comment by ankushdesai** [comment]
@shazqadeer Time to reopen this issue.

**Comment by ankushdesai** [comment]
@shazqadeer float type has been added to the master branch now.
Some of the examples are:
RegressionTests\Feature3Exprs\Correct\float1
RegressionTests\Feature3Exprs\Correct\float2 
RegressionTests\Feature3Exprs\Correct\float3

Will add dynamic and static error regressions now.

**Comment by ankushdesai** [comment]
@shazqadeer  Added few more regressions related to the static and dynamic error.
Closing this issue now.
