### ISSUE TITLE
~\PrtDist\Test\TestSolution.sln does not build.

### ISSUE THREAD

**Issue by lovettchris** [p-org/P#58]
This solution doesn't build, saying PrtDistSerializer.h is missing.  Is this test obsolete?

**Comment by desaiankush** [comment]
This solution is old and may not have caught up with the changes in runtime.
I will fix it. Thanks !

**Comment by shazqadeer** [comment]
@desaiankush : Any word on this issue?

**Comment by desaiankush** [comment]
Fixed.
