### ISSUE TITLE
Hang in EnumerateProofs API in Formula

### ISSUE THREAD

**Issue by shazqadeer** [p-org/P#59]
The P type checker uses the  EnumerateProofs API in Formula to report typing errors.  Ever since typedef's were added to the P language, EnumerateProofs has been known to hang occasionally for ill-typed programs.  I had proposed the following to Ethan earlier.  The  proposal has yet to be implemented.

"My concrete proposal is that Formula provide another API, something called GiveMeOneProof(), that just returns a single proof for a derived fact.  I will use this API rather than EnumerateProofs in the P compiler.  I have looked at the errors generated by the P type checker.  I am confident that P type checking will not be affected by using the alternative API I am proposing.  Even if there is some effect, I will deal with it at the P end.  

To implement GiveMeOneProof efficiently, during the Formula fixpoint whenever a fact is derived for the second time, make a “note” on the edge indicating the derivation.  If the “noted” edges are ignored, the derivation for each fact will be a tree, not a DAG. GiveMeOneProof will return that tree."

**Comment by lovettchris** [comment]
[pbug.zip](https://github.com/p-org/P/files/340080/pbug.zip)

Attached pbug.zip contains a repro of the hang.  run "pc pfiles.p".  The problem appears to be

**Comment by shazqadeer** [comment]
This issue appears to have been resolved for now.
