### ISSUE TITLE
Need enums

### ISSUE THREAD

**Issue by lovettchris** [p-org/P#60]
Can you add "enum" to P which simply maps to a "C" typedef enum ?

**Comment by shazqadeer** [comment]
Something we could add to P are const defintions similar in spirit to the type definitions we already have.

const id: TypeExpr = Expr;

The expression defining the value of id would be allowed to refer to other constant names and the type checker would check that there are no cyclic definitions (similar to typedefs).

Would that be useful?

**Comment by desaiankush** [comment]
What is TypeExpr and expr here ?

I understand expr is the value of the constant "id"

**Comment by shazqadeer** [comment]
TypeExpr is the type of the constant and Expr is the value of the constant.

**Comment by lovettchris** [comment]
Might it be more efficient to define a new type of expression called "ConstTypeExpr" and "ConstExpr" that only allows operations on literal values and other "Const" expressions? Would this speed up the formular compilation because it has less searching to do in StabilizeProofs...

**Comment by shazqadeer** [comment]
I thought more about this issue.  I have decided that constants are not the way to go.  I will instead add enum types, which as Chris suggested, will compile down to C enum types.  Their runtime representation will piggyback on top of the existing representation of P int, i.e., I will not introduce a separate kind for them.

**Comment by desaiankush** [comment]
Sounds good to me

**Comment by shazqadeer** [comment]
I have added support for enum types.  There is one regression test:  Tst/RegressionTests/Feature4DataTypes/Correct/enum1.

I have requested Ella's help in adding more regression tests.

**Comment by shazqadeer** [comment]
Done.  Ella should create separate issues if she detects bugs in the enum implementation.
