### ISSUE TITLE
Allow a goto anywhere

### ISSUE THREAD

**Issue by lovettchris** [p-org/P#61]
It is tedious that I have to "raise someinternalevent" so that I can do "on someinternalevent goto nextstate", why not allow the short hand for this "goto nextstate" from inside a do block?

**Comment by akashlal** [comment]
P# has this: the statement "jump state" does what you describe below. It is implemented as a shorthand for "raise blah" and "on blah goto state". We had to call it jump because goto is a reserved keyword in C#.

Akash

**Comment by shazqadeer** [comment]
We are going to add this feature to P.  It just needs to bubble up to the front of the queue of things to do.

**Comment by shazqadeer** [comment]
Done.
