### ISSUE TITLE
Need a proper printf statement

### ISSUE THREAD

**Issue by lovettchris** [p-org/P#62]
Perhaps modelled like this:

model fun printf(format:str, args:seq[any])
{
}

But P won't let me use strings.  Why no string datatype?  How does "print" work without that?

**Comment by shazqadeer** [comment]
I just defined a print statement in P syntax that takes a string as argument but I did not allow variables to be declared with string type.  Basically, strings are not full-featured types in P just yet.  

What is the issue you are facing? Do you want to print a P data value using a format string like the following?

print "x = {0}", x;  // x is a P variable

**Comment by lovettchris** [comment]
Strings are useful that’s all.  I can’t think of another language that doesn’t have them except assembler…  And by string the most useful is utf-16 encoded strings.

**Comment by shazqadeer** [comment]
Done.
