### ISSUE TITLE
Need string datatype

### ISSUE THREAD

**Issue by lovettchris** [p-org/P#63]
Mapping strings from mavlink to seq[int] is not working well, we need real string datatypes.

type mavlink_log_data
{
    id: int,
    ofs: int,
    count: int,
    data: **string**;
}

**Comment by shazqadeer** [comment]
What are these strings used for?  If they are just names and no computation is done on them, we can just define string as a model (earlier known as foreign) type and avoid the string to seq[int] conversion.

**Comment by shazqadeer** [comment]
@clovett, @ankushdesai: I never got an answer to my question.  Is there any computation performed on values of string types in robotics code or are they just copied from one place to another and printed etc.? The question is whether we should support it natively or as a model type implemented in foreign code.  If we go with the former option, then there is a bunch of work involved, as in deciding what operations to support and giving semantics to our string type.  For the latter, the library can do whatever it wants.

**Comment by lovettchris** [comment]
Given that strings are heavily used in other languages for logic and control, not just debugging, I would recommend a first class string type in P.  I could imagine writing code like this in a P program:

if (done.model == "3dr solo") {
 ....
}

and so on.

**Comment by shazqadeer** [comment]
If we add strings to P, we have to decide what encoding to use.  There are many choices starting from base 8 to base 64 (full Unicode).  Any thoughts?

**Comment by lovettchris** [comment]
utf-8, same as std::string in C++.  See [UTF-8 Everywhere ](http://utf8everywhere.org/) for a good explanation.

**Comment by ankushdesai** [comment]
@shazqadeer: What is the final call on this feature?

**Comment by shazqadeer** [comment]
Chris' argument for putting string in the language are persuasive.  But I would still like to approach the task of adding string to P piecemeal.  At the moment, the priority of a unified reference compiler supersedes everything else.  After that, I would first like to add the string type as a foreign type with operations such as constructors, printing, etc.  We can provide the models and implementation of this type as part of the P distribution to indicate that string is officially supported.  Based on our experience using the library, we can then decide to provide native syntax.

**Comment by ankushdesai** [comment]
P supports string data type now.

**Comment by lovettchris** [comment]
oooh, that's cool :-)
