### ISSUE TITLE
Unable to compile due to "no viable alternative at input"

### ISSUE THREAD

**Issue by fintara** [p-org/P#633]
I have the following simple file `DoesntWork.p`

```
type MyRes = (status: MyStatus);
enum MyStatus {
    ST_SUCCESS,
    ST_ERROR
}
event SomeEvent: int;

machine MyMachine {
    start state Init {
        on SomeEvent do (payload: int) {
            var response: MyRes;
            response = (status = ST_SUCCESS);
        }
    }
}
```

Trying to compile it with `p compile -pf PSrc/DoesntWork.p`  (P version is `2.0.13.0`) and this fails with:

```
Parsing ...
Reverting to LL(*) parsing strategy.
[Parser Error:]
[DoesntWork.p] parse error: line 12:43 no viable alternative at input 'status=ST_SUCCESS)'
```

I must be missing something, but I really cannot find it. 
I've tried to have the types' and events' names start with a lowercase letter, but it doesn't seem to matter.

(For context - I'm trying to write my own "client-server project" based on the 1_ClientServer tutorial. The tutorial compiles just fine. This is the minimal reproducible example that shows the issue.)

**Comment by ankushdesai** [comment]
``` response = (status = ST_SUCCESS);```
should be
```response = (status = ST_SUCCESS,);```
to indicate that its a tuple. 

Sorry for this weirdness :)

**Comment by ankushdesai** [comment]
There isnt an easy way to distinguish between a named tuple value (with single field in it) and parenthesis around a value: basically, we need the comma for the parser to distinguish between `(5)` and `(5,)` first is a value `5` and second is a tuple with one element `5` of type `int`. Not sure how to fix this without changing the way we represent tuple values. Any suggestions :)

**Comment by shazqadeer** [comment]
It looks like P is in elite company. Rust takes the same approach. See the code on lines 42 and 43 [here](https://doc.rust-lang.org/rust-by-example/primitives/tuples.html). 

I suppose explaining the issue in the documentation should be adequate.

**Comment by ankushdesai** [comment]
Haha. Thanks for this pointer. Now people will no longer complain, as we can say we are same Rust ;). Elite club.

**Comment by fintara** [comment]
Thanks, it works!

Just to mention, such syntax can be seen in Python code too - so it's not that weird, one just has to remember about it. :sweat_smile:

**Comment by shazqadeer** [comment]
But I still find it weird that the error is reported in the parsing stage (and the error message is not helpful either). I would have expected parsing to succeed but type checking to fail with a better error message.

**Comment by ankushdesai** [comment]
@shazqadeer the parsing fails `response = (status = ST_SUCCESS);` as in this case `(status = ST_SUCCESS)` gets parsed as an assignment statement and we then the parser starts complaining, I need to think about how this can help fixed.
