### ISSUE TITLE
Infinite loop in Timer module

### ISSUE THREAD

**Issue by aman-goel** [p-org/P#642]
PCover is catching a cycle/infinite-loop in P projects that use the [Timer](https://github.com/p-org/P/tree/master/Tutorial/Common/Timer) project (e.g., [TwoPhaseCommit](https://github.com/p-org/P/tree/master/Tutorial/2_TwoPhaseCommit)).

The issue is due to an infinite loop in how eDelayedTimeout is modeled: https://github.com/p-org/P/blob/master/Tutorial/Common/Timer/PSrc/Timer.p#L22-L33. There exists a path where the `else` branch can be taken over and over again, resulting in an infinite loop.

```
state TimerStarted {
    defer eStartTimer;
    entry {
      if($)
      {
        send client, eTimeOut;
        goto WaitForTimerRequests;
      }
      else
      {
        send this, eDelayedTimeOut;
      }
    }
    on eDelayedTimeOut goto TimerStarted;
    on eCancelTimer goto WaitForTimerRequests;
  }
}
```

PCover is currently reporting this behavior as a liveness violation due to a cycle. For bug finding, the probability of triggering this behavior is near to zero ( 1/(2^1000) for 1000 iterations of this loop).

A solution is to bound the number of times this loop is executed when creating the timer. How does that sound? Do we want a default bound (say 3) or enforce a user-supplied value or both?

**Comment by ankushdesai** [comment]
How is this being reported as a liveness violation?

**Comment by aman-goel** [comment]
Explicit-state engine if encounters the same state twice at different depths in the same execution reports that as a cycle detected. It reports such cycles as a liveness violation due to non termination, since the corresponding state cycle can be repeated infinite times.

**Comment by ankushdesai** [comment]
I will think about how to fix this issue and get back to you. Making it finite is not going to solve the issue completely.
