### ISSUE TITLE
High quality P Icon

### ISSUE THREAD

**Issue by josanri** [p-org/P#676]
https://github.com/p-org/P/blob/master/Icon/icon.png
P Language Icon is nowadays a 119x119 png with a low resolution. As I needed the logo for a presentation I decided not to use a logo that could easily pixelate on a big screen so I "remastered" the logo on and attach the results to this issue (removed the small white shadows).
I understand this is not a important subject and is not related to this repository code, but here are the results on png and svg:
![p_logo png](https://github.com/p-org/P/assets/87527355/d4821ad4-e164-4454-8c52-ed2e37d54758)
![p_logo svg](https://github.com/p-org/P/assets/87527355/b125e7db-447d-4bcb-913b-e5fff152bd00)

**Comment by ankushdesai** [comment]
Thank you for this help! This has been a long pending task on our list :).

**Comment by ankushdesai** [comment]
Have saved them! Thanks.
