### ISSUE TITLE
"defer" and "ignore" statements not documented

### ISSUE THREAD

**Issue by toddlipcon** [p-org/P#677]
These keywords are mentioned in the BNF description of the grammar (and used in one example), but not explained how they work. They should probably be somewhere in the state machine or event docs.

**Comment by ankushdesai** [comment]
Yes, this has been a long pending todo item. This this page is remaining to be filled: https://p-org.github.io/P/manual/statemachines/

Will be finished soon. Thanks for pointing out.

Defer: https://github.com/p-org/P/discussions/515
Ignore: Just drops the message. You can think of ignore as a short hand for 
```
ignore E1; 
on E1 do { // nothing };
```
