### ISSUE TITLE
This produces bad 'C' output

### ISSUE THREAD

**Issue by lovettchris** [p-org/P#68]
This program produces C code that doesn't compile:

	model type float32 = int;
	
	//// Converts an integer to float
	model fun IntToFloat32(val: int) : float32
	{
	   return default(float32); 
	} 
	
	
	model fun AddFloat32(op1: float32, op2: float32) : float32
	{
	   return default(float32);
	} 
	
	
	main machine Test
	{
	  start state Init {
	    entry {
	      var f: float32;
	      f = IntToFloat32(1);
	      f = AddFloat32(f, IntToFloat32(1000)); 
	    }
	  }
	}

file:///d:/temp/bug.p(28): error C2084: function 'PRT_VALUE *P_FUN_Test_ANON1_IMPL(PRT_MACHINEINST *)' already has a body
bug.c(272): note: see previous definition of 'P_FUN_Test_ANON1_IMPL'

**Comment by shazqadeer** [comment]
I have checked in a fix.
