### ISSUE TITLE
Upgrade to Newer .Net Version

### ISSUE THREAD

**Issue by furesoft** [p-org/P#690]

**Comment by ankushdesai** [comment]
Thanks for bringing this up. We will update to new version soon, but its not planned when. Mostly this summer.

**Comment by ankushdesai** [comment]
The support for .NET 6 ends Nov 12, 2024.

**Comment by ankushdesai** [comment]
@mchadalavada lets try to resolve this issue and create a version 2.1.0. Roll this out in March.

**Comment by ankushdesai** [comment]
P version 2.1.0 upgrades P to .Net 8. Thanks!
