### ISSUE TITLE
[modp] Cannot compare machine value with null

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#7]
I would like to be able to compare machine values with null. E.g.
```
assert SomeMachineV == null;
```

but I get the error:
```
Values of type machine or interface cannot be compared
```

**Comment by paulthomson** [comment]
Here is an example:
```
event eUpdate;
event eDone;

module MyModule 
{
	machine Manager {

	    var SomeMachineV : machine;
	    var AnotherMachineV : seq[machine];

	    start state Init {
	        on eUpdate goto Thinking with
	        {
	            assert SomeMachineV == null;
	        };
	    }

	    state Thinking {
	        on eDone goto Done with 
	        
	        {
	            var machineList : seq[machine];
	            // DELETE next line to suppress compilation error
	            machineList = AnotherMachineV;
	        };
	    }

	    state Done {

	    }

	}
}
```

**Comment by desaiankush** [comment]
Shaz, mentioned that you are getting inconsistency in the error reported. Sometimes the type checker complains and sometimes it doesnt. Can you please provide an example for both ?

**Comment by desaiankush** [comment]
I have fixed this issue and added the regression in 
P\Tst\RegressionTests\Feature4DataTypes\StaticError\comparemachinetype

**Comment by shazqadeer** [comment]
@desaiankush: As far as I understand, this issue happens only in the modp branch.  Is your code update in the modp branch?  Also, do you allow comparison with null now?

**Comment by ellab123** [comment]
Hi, Ankush,

Have you committed this test? I just did “git pull”, and I don’t see it.

Thank you,

Ella

**Comment by shazqadeer** [comment]
I believe this test is in the modp branch.

**Comment by ellab123** [comment]
Shaz,

I’m preparing to push *breaking* change in the regression tool.
Wouldn’t that break regression testing in that other branch at some point?

Ella

**Comment by desaiankush** [comment]
Hi Ella,

What are the changes that you are making to the testing tool.
Can we do it in stages so that the modp branch can also start using it
without much changes.

**Comment by ellab123** [comment]
Hi, Ankush,

The changes affect “testconfigXX.txt” files (where XX stands for Pc or Prt or Zing) and simplify parameters in those:
- eliminated parameters: runPc, runPrt, runZing, acc, add

-          renamed parameters:

“incXX” is “now “inc”

“argXX” is now “arg”

-          all testconfigXX.txt files renamed into “testconfig.txt”
I’m planning on pushing the changes today.

Let me know if you need help with making these changes in the mod branch.

Ella
