### ISSUE TITLE
list containment

### ISSUE THREAD

**Issue by lovettchris** [p-org/P#75]
You provide "in" operator for maps, but not lists.  Any reason for that limitation?  Sometimes it is useful to know if an object has already been added to a list...

**Comment by shazqadeer** [comment]
Unlike the "in" operator for maps, the "in" operator for sequences could be easily implemented by the programmer.  At the time all this was done I couldn't think of a more efficient implementation that I would do in the runtime.  But we could revisit and add this operator on sequences also.

**Comment by ankushdesai** [comment]
We should support contains operations in the new Compiler.

**Comment by alexreinking** [comment]
As long as programmers understand that `in` on a list is an O(n) operation, there's no reason we can't support this. Python has the same semantics.

**Comment by shazqadeer** [comment]
I am fine with adding this operator.  Good idea.

**Comment by ankushdesai** [comment]
List Containment is now supported in P.
https://github.com/p-org/P/pull/218
