### ISSUE TITLE
Compiling generated C# code FAILED

### ISSUE THREAD

**Issue by PoorlyDefinedBehaviour** [p-org/P#776]
I'm trying to use P for the first time and got this while compiling a basic project with Peasy on vscode:

Reporting since the error message asked me to. 

Edit: deleting the output folder seems to have fixed it, reporting just in case.

<details>
`
Executing task: cd /Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/ ; p compile 

.. Searching for a P project file *.pproj locally in the current folder
.. Found P project file: /Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/project.pproj
----------------------------------------
==== Loading project file: /Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/project.pproj
....... includes p file: /Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PSrc/Thread.p
....... includes p file: /Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PSrc/Module.p
....... includes p file: /Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PSpec/FinalValueIsCorrect.p
....... includes p file: /Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PTst/TestDriver.p
....... includes p file: /Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PTst/Testscript.p
----------------------------------------
Parsing ...
Type checking ...
----------------------------------------
Code generation for CSharp...
Generated AddIntegers.cs.
Compiling generated code...
Reusing existing /Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/Test.cs
[CSharp Compiling Generated Code:]
Compiling generated C# code FAILED!
MSBuild version 17.9.8+b34f75857 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/generatedOutput.cs(24,28): error CS0111: Type 'PHelper' already defines a member called 'InitializeInterfaces' with the same parameter types [/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/AddIntegers.csproj]
/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/generatedOutput.cs(33,28): error CS0111: Type 'PHelper' already defines a member called 'InitializeEnums' with the same parameter types [/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/AddIntegers.csproj]
/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/AddIntegers.cs(292,15): warning CS0108: 'FinalValueIsCorrect.Assert' hides inherited member 'Monitor.Assert(bool)'. Use the new keyword if hiding was intended. [/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/AddIntegers.csproj]

Build FAILED.

/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/AddIntegers.cs(292,15): warning CS0108: 'FinalValueIsCorrect.Assert' hides inherited member 'Monitor.Assert(bool)'. Use the new keyword if hiding was intended. [/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/AddIntegers.csproj]
/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/generatedOutput.cs(24,28): error CS0111: Type 'PHelper' already defines a member called 'InitializeInterfaces' with the same parameter types [/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/AddIntegers.csproj]
/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/generatedOutput.cs(33,28): error CS0111: Type 'PHelper' already defines a member called 'InitializeEnums' with the same parameter types [/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/AddIntegers.csproj]
    1 Warning(s)
    2 Error(s)

Time Elapsed 00:00:00.58

[THIS SHOULD NOT HAVE HAPPENED, please report it to the P team or create a GitHub issue]
Compiling generated C# code FAILED!
MSBuild version 17.9.8+b34f75857 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/generatedOutput.cs(24,28): error CS0111: Type 'PHelper' already defines a member called 'InitializeInterfaces' with the same parameter types [/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/AddIntegers.csproj]
/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/generatedOutput.cs(33,28): error CS0111: Type 'PHelper' already defines a member called 'InitializeEnums' with the same parameter types [/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/AddIntegers.csproj]
/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/AddIntegers.cs(292,15): warning CS0108: 'FinalValueIsCorrect.Assert' hides inherited member 'Monitor.Assert(bool)'. Use the new keyword if hiding was intended. [/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/AddIntegers.csproj]

Build FAILED.

/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/AddIntegers.cs(292,15): warning CS0108: 'FinalValueIsCorrect.Assert' hides inherited member 'Monitor.Assert(bool)'. Use the new keyword if hiding was intended. [/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/AddIntegers.csproj]
/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/generatedOutput.cs(24,28): error CS0111: Type 'PHelper' already defines a member called 'InitializeInterfaces' with the same parameter types [/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/AddIntegers.csproj]
/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/generatedOutput.cs(33,28): error CS0111: Type 'PHelper' already defines a member called 'InitializeEnums' with the same parameter types [/Users/brunofelipefrancisco/dev/formal-methods/add_integers_p_lang/PGenerated/CSharp/AddIntegers.csproj]
    1 Warning(s)
    2 Error(s)

Time Elapsed 00:00:00.58

~~ [PTool]: Thanks for using P! ~~
`
</details>

Project folder looks like this:
```
PGenerated      PSpec           PSrc            PTst            project.pproj
```

The `.pproj` file that I copied from the [ClientServer](https://github.com/p-org/P/blob/master/Tutorial/1_ClientServer/ClientServer.pproj) example:
```xml
<!-- P Project file for the Client Server example -->
<Project>
<ProjectName>AddIntegers</ProjectName>
<InputFiles>
	<PFile>./PSrc/</PFile>
	<PFile>./PSpec/</PFile>
	<PFile>./PTst/</PFile>
</InputFiles>
<OutputDir>./PGenerated/</OutputDir>
</Project>
```

**Comment by ankushdesai** [comment]
Can you please also copy the program that led to this error. If possible zip the entire folder. Thanks!
