### ISSUE TITLE
removing main keyword

### ISSUE THREAD

**Issue by shazqadeer** [p-org/P#78]
I would like to remove the "main" keyword from the language.  The main keyword is used only for testing purposes.  My suggestion is to use as the main machine the one machine whose name is Main.

**Comment by teja5832** [comment]
If there is no main keyword or an isMain attribute, why is that not reflected in the Regression Tests?

**Comment by shazqadeer** [comment]
Ella is in the process of updating the tests and the golden outputs.

**Comment by teja5832** [comment]
Wow. Sorry for that!

**Comment by shazqadeer** [comment]
The latest commit (by Ella) has changed the tests.

**Comment by ivanov** [comment]
Section 2 of the P tutorial/manual still has the `main` keyword in the PingPong sample program.
