### ISSUE TITLE
[Bug report] null is not assignable to type int but it is comparable

### ISSUE THREAD

**Issue by PoorlyDefinedBehaviour** [p-org/P#782]
Assigning `null` to a variable of type `int` is a compile error:
```p
machine Main {
  start state Init {
    entry {
      var x: int;
      x = null;
    }
  }
}
```

```
// p compile

Parsing ...
Type checking ...
[Error:]
[PSrc/Main.p:5:11] got type: any, expected: int
```

But comparing `null` to a variable of type `int` compiles:
```p
machine Main {
  start state Init {
    entry {
      var x: int;
      if(x == null) {
        
      }
    }
  }
}
```

**Comment by ankushdesai** [comment]
Thanks! I will take a look at this but it is a definite bug.

**Comment by PoorlyDefinedBehaviour** [comment]
> Thanks! I will take a look at this but it is a definite bug.

I could try fixing it if you haven't started yet 👍

**Comment by ankushdesai** [comment]
We really welcome contributions from the community! Otherwise, I will get to this later this week. Thanks!

**Comment by ankushdesai** [comment]
Thanks this PR will fix the issue: https://github.com/p-org/P/pull/797
