### ISSUE TITLE
Statically get type of a variable

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#8]
It might be nice to be able to statically get the type of a variable.

E.g.
```
var MachineList : seq[machine];
...

MachineList = default(typeof(MachineList));

```

Or allow `default` to take a variable name instead of a type. 

```
MachineList = default(MachineList);
```

**Comment by paulthomson** [comment]
I think this is a bit like [decltype](http://en.cppreference.com/w/cpp/language/decltype) in C++. 

It might also be useful to get the (return) type of functions so that you don't have to duplicate its type or make the return type a named type. E.g.

```
public fun MyFunction(count : int) : (result : int, newCount : int)
{
    //...
    return (result = ..., newCount = count);
}

// ...
entry
{
    var temp : typeof(MyFunction);
    var result : int;
    var count : int;
    // ...

    temp   = MyFunction(count);
    result = temp.result;
    count  = temp.newCount;

    //..
}

```

Alternatively, can I do something like the following?
```
(result, count) = MyFunction(count);
```

**Comment by shazqadeer** [comment]
This one seems low-priority for now since the ability to create type synonyms gets you most of the effect you want.  We can revisit it later.
