### ISSUE TITLE
Need a way to build on *nix systems - attached some scripts

### ISSUE THREAD

**Issue by teja5832** [p-org/P#80]
We need a way to build this on *nix systems[I work on a Mac :P]
Here's a beginning - build shell scripts corresponding to the ones on Bld/ 
It has been zipped as GitHub doesn't seem to accept sh files as attachments.
[Archive.zip](https://github.com/p-org/P/files/386749/Archive.zip)

**Comment by teja5832** [comment]
My build script gives the following error when run - 

"/Users/suryatejachavali/P/P.sln" (default target) (1) ->
"/Users/suryatejachavali/P/Src/PrtDist/Core/PrtDist.vcxproj" (default target) (2) ->
  /Users/suryatejachavali/P/Src/PrtDist/Core/PrtDist.vcxproj(27,3): error MSB4019: The imported project "/Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.


"/Users/suryatejachavali/P/P.sln" (default target) (1) ->
"/Users/suryatejachavali/P/Src/PrtDist/PrtWinUser.vcxproj" (default target) (3) ->
  /Users/suryatejachavali/P/Src/PrtDist/PrtWinUser.vcxproj(66,3): error MSB4019: The imported project "/Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.


"/Users/suryatejachavali/P/P.sln" (default target) (1) ->
"/Users/suryatejachavali/P/Src/PrtDist/NodeManager/NodeManager.vcxproj" (default target) (4) ->
  /Users/suryatejachavali/P/Src/PrtDist/NodeManager/NodeManager.vcxproj(26,3): error MSB4019: The imported project "/Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.


"/Users/suryatejachavali/P/P.sln" (default target) (1) ->
"/Users/suryatejachavali/P/Src/Prt/IDL/PrtIDL.vcxproj" (default target) (6) ->
  /Users/suryatejachavali/P/Src/Prt/IDL/PrtIDL.vcxproj(35,3): error MSB4019: The imported project "/Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.


"/Users/suryatejachavali/P/P.sln" (default target) (1) ->
"/Users/suryatejachavali/P/Src/Pc/Compiler/Compiler.csproj" (default target) (7) ->
(BeforeBuild target) -> 
  /Users/suryatejachavali/P/Src/Pc/Compiler/Compiler.csproj : error : /Users/suryatejachavali/P/Src/Pc/Compiler/Domains/P.4ml: Method 'TaskLoggingHelper.LogMessage' not found.


"/Users/suryatejachavali/P/P.sln" (default target) (1) ->
"/Users/suryatejachavali/P/Src/Parsers/CParser/CParser.csproj" (default target) (8) ->
(KillCompilerService target) -> 
  /Users/suryatejachavali/P/Bld/Targets/compiler.targets(42,5): error MSB4018: The "KillProcess" task failed unexpectedly. [/Users/suryatejachavali/P/Src/Parsers/CParser/CParser.csproj]
/Users/suryatejachavali/P/Bld/Targets/compiler.targets(42,5): error MSB4018: This is an unhandled exception from a task -- PLEASE OPEN A BUG AGAINST THE TASK OWNER. [/Users/suryatejachavali/P/Src/Parsers/CParser/CParser.csproj]
/Users/suryatejachavali/P/Bld/Targets/compiler.targets(42,5): error MSB4018: System.InvalidOperationException: Process has exited, so the requested information is not available. [/Users/suryatejachavali/P/Src/Parsers/CParser/CParser.csproj]
/Users/suryatejachavali/P/Bld/Targets/compiler.targets(42,5): error MSB4018:   at System.Diagnostics.Process.get_ProcessName () <0x6fbb750 + 0x001f3> in <filename unknown>:0  [/Users/suryatejachavali/P/Src/Parsers/CParser/CParser.csproj]
/Users/suryatejachavali/P/Bld/Targets/compiler.targets(42,5): error MSB4018:   at (wrapper remoting-invoke-with-check) System.Diagnostics.Process:get_ProcessName () [/Users/suryatejachavali/P/Src/Parsers/CParser/CParser.csproj]
/Users/suryatejachavali/P/Bld/Targets/compiler.targets(42,5): error MSB4018:   at InlineCode.KillProcess.Execute () <0x6fbb220 + 0x0003b> in <filename unknown>:0  [/Users/suryatejachavali/P/Src/Parsers/CParser/CParser.csproj]
/Users/suryatejachavali/P/Bld/Targets/compiler.targets(42,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () <0x2deca90 + 0x0004d> in <filename unknown>:0  [/Users/suryatejachavali/P/Src/Parsers/CParser/CParser.csproj]
/Users/suryatejachavali/P/Bld/Targets/compiler.targets(42,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder+<ExecuteInstantiatedTask>c__async4.MoveNext () <0x2de8398 + 0x00665> in <filename unknown>:0  [/Users/suryatejachavali/P/Src/Parsers/CParser/CParser.csproj]

**Comment by teja5832** [comment]
Changed scripts to make msbuild into xbuild and got the error	
/Users/suryatejachavali/P/P.sln (default targets) ->
(Build target) ->
/Users/suryatejachavali/P/Src/Parsers/CParser/CParser.csproj (default targets) ->				/Users/suryatejachavali/P/Bld/Targets/compiler.targets (KillCompilerService target) ->
: error : Error initializing task KillProcess: Not registered task KillProcess.

**Comment by lovettchris** [comment]
Ah, this is something I added, because I made the pc.exe compiler into a service that can be shared across invocations in order to make it faster.  If xbuild has no way to kill processes then you could make the "/shared" option itself optional and the killprocess only needs to be invoked when "/shared" is used.  Or find a way to kill processes using xbuild...

**Comment by teja5832** [comment]
Another question: in what part of the build process is P.4ml.g.cs generated?

**Comment by lovettchris** [comment]
Inside Compiler.csproj you will see a custom target called "GenerateCodeFromLex" and another "GenerateParserCodeFromGrammar".  These use GPlex45.exe and GPPG45.exe command line tools.  These are managed tools, they might "just run" on Mono, or do Mono apps need recompilation?  If you need to rebuild them for mono then you can find the code here: http://gppg.codeplex.com/ and here http://gplex.codeplex.com/

**Comment by teja5832** [comment]
After a whole barrage of bugs and issues, I managed to get to a point where it gives me an error message which says:
/Users/suryatejachavali/P/P.sln (default targets) ->(Build target) -> /Users/suryatejachavali/P/Src/Pc/Compiler/Compiler.csproj (default targets) -> (BeforeBuild target) -> /Users/suryatejachavali/P/Src/Pc/Compiler/Compiler.csproj: error : /Users/suryatejachavali/P/Src/Pc/Compiler/Domains/P.4ml: Method 'TaskLoggingHelper.LogMessage' not found.

I did the following:
Comment out the kill process thing in compiler.targets - (need to add an if condition on $(OS))
Make a change to line 240 of Compiler.csproj due to an error in the xbuild parser, as 
  <FormulaGenFiles Include="@(EmbeddedResource->'%(FullPath)')" Condition="'%(EmbeddedResource.Generator)' == 'FormulaCodeGenerator'" />
[Notice the extra '' around %(EmbeddedResource.Generator)] This is in accordance with https://bugzilla.xamarin.com/show_bug.cgi?id=19678 and http://stackoverflow.com/questions/28774085/using-microsoft-visualstudio-web-targets-from-mono

**Comment by teja5832** [comment]
[Archive.zip](https://github.com/p-org/P/files/387253/Archive.zip)
Latest version of scripts

**Comment by lovettchris** [comment]
'TaskLoggingHelper.LogMessage' is a core concept of MSBuildTasks - it is how the custom task communicates back to the VS user to tell them what is going on.  I'm surprised this isn't supported by xbuild.  But the call to LogMessage would be inside FormulaCodeGeneratorTask.dll.  The code for that lives here: https://github.com/Microsoft/formula/tree/master/Src/Extensions/FormulaCodeGeneratorTask, and the call to LogMessage is here: genTask.Log.LogMessage("Transformed {0} -> {1}", InputFile, outputFile);

**Comment by teja5832** [comment]
The xbuild man page has the following to say about MSBuildExtensionsPath. This environment variable is the place where it looks for the relevant DLL's. 
       MSBuildExtensionsPath
              MSBuild extensions are usually installed in $(MSBuildExtensionsPath), which xbuild resolves to $prefix/lib/mono/xbuild . When used in Import, like:
                <Import Project="$(MSBuildExtensionsPath)\TestTargets.targets"/>

              xbuild tries various values for the msbuild property $(MSBuildExtensionsPath), in order:

                1. Paths specified in the environment variable $MSBuildExtensionsPath.
                2. /Library/Frameworks/Mono.framework/External/xbuild on Mac OSX.
                3. $XDG_CONFIG_HOME/xbuild/tasks (or Environment.SpecialFolder.ApplicationData)
                4. $prefix/lib/mono/xbuild (default location)
Anywhere else in the project files, $(MSBuildExtensionsPath) will always resolve to the default location. This is a xbuild-only  feature. This  is also  applicable  for the properties $(MSBuildExtensionsPath32) and $(MSBuildExtensionsPath64), and the environment variables have the corresponding  names - MSBuildExtensionsPath32/64 .


[Src:http://manpages.ubuntu.com/manpages/precise/man1/xbuild.1.html]
I tried the following strategies, all to no avail:

1. Add these lines to Compiler.csproj
  <PropertyGroup>
    <MSBuildExtensionsPath Condition="'$(OS)'=='Unix'">
      /Library/Frameworks/Mono.framework/Versions/4.4.1/lib/mono/xbuild/14.0/bin
    </MSBuildExtensionsPath>
    <MSBuildExtensionsPath32 Condition="'$(OS)'=='Unix'">
      /Library/Frameworks/Mono.framework/Versions/4.4.1/lib/mono/xbuild/14.0/bin
    </MSBuildExtensionsPath32>
    <MSBuildExtensionsPath64 Condition="'$(OS)'=='Unix'">
      /Library/Frameworks/Mono.framework/Versions/4.4.1/lib/mono/xbuild/14.0/bin
    </MSBuildExtensionsPath64>
  </PropertyGroup>

2. Add these variables with the /p flag to the xbuild command
3. Set the environment vars in bash.

None of these seem to have yielded any fruit.

**Comment by teja5832** [comment]
Why was the Unix/CMake-based build rolled back?

**Comment by desaiankush** [comment]
@teja5832 It needed some more fixes. Should be available from tomorrow mostly.

**Comment by teja5832** [comment]
Build fails on a Mac running XBuild Engine Version 14.0 and Mono, Version 4.4.1.0. After some searching, it seems this is because CodeAnalysis works only in .NET 4.6+. There seems to be a NuGet workaround to this, but am not sure...

Here's the exact error message:

/Users/suryatejachavali/P/P.sln (default targets) ->
(Build target) ->
/Users/suryatejachavali/P/Src/Pc/Compiler/TestRoslyn/TestRoslyn.csproj (default targets) ->
/Library/Frameworks/Mono.framework/Versions/4.4.1/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

	Program.cs(1,17): error CS0234: The type or namespace name `CodeAnalysis' does not exist in the namespace `Microsoft'. Are you missing an assembly reference?
	Program.cs(2,17): error CS0234: The type or namespace name `CodeAnalysis' does not exist in the namespace `Microsoft'. Are you missing an assembly reference?
	Program.cs(4,17): error CS0234: The type or namespace name `CodeAnalysis' does not exist in the namespace `Microsoft'. Are you missing an assembly reference?
	Program.cs(5,17): error CS0234: The type or namespace name `CodeAnalysis' does not exist in the namespace `Microsoft'. Are you missing an assembly reference?


Thanks again!

**Comment by desaiankush** [comment]
You need to do nuget restore P.sln.
Will add that to the build.sh (sometime end of day) and let you know.

**Comment by desaiankush** [comment]
Thanks to @thisiscam 
We have a version of P working on Ubuntu/Mac and Windows.
@teja5832  Please try it and let us know.
Close the issue if you are satisfied :)

**Comment by desaiankush** [comment]
Closing the issue considering that the pc builds and runs on ubuntu and mac.
