### ISSUE TITLE
invalid assignment. right hand side is not a subtype of left hand side

### ISSUE THREAD

**Issue by lovettchris** [p-org/P#82]
Cannot assign an enum to an int in this case:

```
    enum PX4_CUSTOM_MAIN_MODE {
        PX4_CUSTOM_MAIN_MODE_NONE,
        PX4_CUSTOM_MAIN_MODE_MANUAL,
        PX4_CUSTOM_MAIN_MODE_ALTCTL,
        PX4_CUSTOM_MAIN_MODE_POSCTL,
        PX4_CUSTOM_MAIN_MODE_AUTO,
        PX4_CUSTOM_MAIN_MODE_ACRO,
        PX4_CUSTOM_MAIN_MODE_OFFBOARD,
        PX4_CUSTOM_MAIN_MODE_STABILIZED,
        PX4_CUSTOM_MAIN_MODE_RATTITUDE
    }
        var mode: int;
    mode = PX4_CUSTOM_MAIN_MODE_POSCTL;
```

but it works if I add explicit integer values on the enum like this:
        enum PX4_CUSTOM_MAIN_MODE {
            PX4_CUSTOM_MAIN_MODE_NONE = 0,
            PX4_CUSTOM_MAIN_MODE_MANUAL = 1,
            PX4_CUSTOM_MAIN_MODE_ALTCTL = 2,
            PX4_CUSTOM_MAIN_MODE_POSCTL = 3,
            PX4_CUSTOM_MAIN_MODE_AUTO = 4,
            PX4_CUSTOM_MAIN_MODE_ACRO = 5,
            PX4_CUSTOM_MAIN_MODE_OFFBOARD = 6,
            PX4_CUSTOM_MAIN_MODE_STABILIZED = 7,
            PX4_CUSTOM_MAIN_MODE_RATTITUDE = 8
        }

why have this restriction?

**Comment by shazqadeer** [comment]
I thought that is the design we decided on together :-)

The idea here is that the programmer wants to treat enum values as their own type unless explicit integer constants are attached to them.  It gives them the control and still gets more out of the type checker.

**Comment by lovettchris** [comment]
Well in practice it seemed inconsistent and undiscoverable.  Why not assign default integers when none are specified so the conversion is always possible?  This is how enums work in other languages.

**Comment by ankushdesai** [comment]
@shazqadeer I forgot what is the story of enum implementation right now?
Can we close this issue?

**Comment by shazqadeer** [comment]
The final status is that if integers are not explicitly specified, then default values are picked.  enum types are now subtypes of int always.  Take a look at this sample: Tst\RegressionTests\Feature4DataTypes\Correct\enum2\enum2.p
