### ISSUE TITLE
This is becoming tedious, I need C# "await" semantics...

### ISSUE THREAD

**Issue by lovettchris** [p-org/P#83]
I'm finding this pattern show up over and over, I send a message and wait for a response either "CommandSucceeded" or "CommandFailed" and then proceed accordingly.  In C# this "**async**" pattern is one line of code thanks to the "**await**" operator.  I think I'm asking for a spin on your "receive" statement that can "receive any response" so I can then check what that response is.  But my goal is to greatly reduce the amount of code needed to do this pattern.  So my challenge to you is "how small can you make this code?"

	state RequestAutoMode {
		entry {
			send commander, Command, (caller=this, cmd=mav_cmd_do_set_mode);			
		}
		on CommandSucceeded do (cmd:int) {
			if (cmd == mav_cmd_do_set_mode) {
				autoMode = true;
				raise fmom_finish_mission_ready;
			}
		}

		on CommandFailed do (cmd:int) {
			if (cmd == mav_cmd_do_set_mode) {	
		                  raise fmom_finish_mission_failed;
			}
		}

		on fmom_finish_mission_ready goto Ready;
		on fmom_finish_mission_failed goto Standby;
	}

**Comment by desaiankush** [comment]
One design pattern I have used for handling this type of scenarios is to embedded the events "CommandSucceeded ", "CommandFailed"... into the payload of a parent event "ResponseAck".

Now you can write a single action handler 
`
on ResponseAck (payload)
{
if(payload.ev == CommandSucceeded) ..
else ....
}
`

This will reduce the number of handlers you will have to write.

**Comment by paulthomson** [comment]
Can you do something like this? I don't have P to hand right now to check. And is this still too verbose anyway? 

```
state RequestAutoMode {
    entry {
        send commander, Command, (caller=this, cmd=mav_cmd_do_set_mode);
        receive {
            case CommandSucceeded : (cmd:int) {
                if (cmd == mav_cmd_do_set_mode) {
                    autoMode = true;
                    raise fmom_finish_mission_ready;
                }
            }
            case CommandFailed : (cmd:int) {
                if (cmd == mav_cmd_do_set_mode) {   
                    raise fmom_finish_mission_failed;
                }
            }
        }

    on fmom_finish_mission_ready goto Ready;
    on fmom_finish_mission_failed goto Standby;
}
```

**Comment by desaiankush** [comment]
@paulthomson 
Note that receive blocks all other events which is not what Chris is looking for.

**Comment by paulthomson** [comment]
Ah I see. I wasn't sure from the example since there are only two handlers.

**Comment by lovettchris** [comment]
Closer, how about:


state RequestAutoMode {

    entry {

        var answer = await request commander, Command, (caller=this, cmd=mav_cmd_do_set_mode);

        if (answer.event == CommandSucceeded) {

            autoMode = true;

            goto Ready;

        } else {

            goto Standby;

        }

    }

}

where the semantics of “await request” is to send the message, then wait for reply from that machine (so the “request response” pattern becomes a first class citizen), gather that reply in a variable that contains the event and the payload, here I only need the event since this semantics now allow me to ignore the payload.  Then let me also do a direct “goto” anywhere instead of raise and goto in two steps.  Now this is getting down to the size I wanted… and it also means I don’t even need to invent a state for this at all, so state RequestAutoMode goes away also and I include this code inline where previously I was calling goto RequestAutoMode.

And I don’t want this “sendreceive” to block my current state from receiving other messages.

It’s probably all crazy, but I thought I’d let you chew on it…

**Comment by paulthomson** [comment]
I wrote an actors framework somewhat recently where, essentially, each actor/machine had its own main "mailbox". But you could also create additional mailboxes.

So you could do (similar to P/P#):

```
Object o = runtime.CurrentMailbox().Receive();
// use o..
```

Or you could do:

```
var tempMailbox = runtime.CreateMailBox<string>();
runtime.Send(otherActor, new Msg(tempMailbox));
string result = tempMailbox.Receive();
```

Thus, you would essentially have your own "channel" on which to receive the message. The machine still could not process other messages though---they still go into the main mailbox, but cannot be processed until the handler has returned. But I think allowing other event handers to run while blocked at a `receive` could be a feature request on its own!

* Doing a "goto" anywhere: I have also thought about having this! One downside that might be argued is that now the state transitions are no longer "declarative". But, as we can clearly see, they are not really declarative anyway because instead we just use raise inside branches! This could also be a feature request on its own.

* Another suggestion that might be relevant: in P#, they now just have Events (no payloads). Event types have fields so there is no need for a payload. So you can switch on the event type and access the fields of the event object, which is slightly less verbose. I guess this might be tricky to do in P's type system though.

**Comment by shazqadeer** [comment]
From what I can see, the main issue is the absence of a goto statement in P.  I am going to put that at the top of the stack now.  With that in place, the code will get much more compact.

**Comment by shazqadeer** [comment]
I have two other syntactic suggestions that might help.  I would like your opinion.
1. Make the type declaration in the payload parameter of an event handler optional.  For example:

on CommandSucceeded do (cmd) {
        if (cmd == mav_cmd_do_set_mode) {
            autoMode = true;
            raise fmom_finish_mission_ready;
        }
    }

Of course, in some positions such as the entry or exit function, it will not be optional.

2. Remove the : in a case statement.  I feel  that the : as a separator is not adding much for a case statement.  With all that, send/receive would look like the following.

state RequestAutoMode {
    entry {
        send commander, Command, (caller=this, cmd=mav_cmd_do_set_mode);
        receive {
            case CommandSucceeded (cmd) {
                if (cmd == mav_cmd_do_set_mode) {
                    autoMode = true;
                    goto Ready;
                }
            }
            case CommandFailed (cmd) {
                if (cmd == mav_cmd_do_set_mode) {   
                    goto Standby;
                }
            }
        }
}

**Comment by desaiankush** [comment]
@shazqadeer 
I am fine with removing the type of payload load from handlers. But I like the ":" after case.

Also, how up the stack is the addition of "goto". I guess we can add goto and the changes you suggested above. Then we should *Freeze* feature addition in P until we are done with modp integration and zing branch.

**Comment by shazqadeer** [comment]
I have added goto statement to P.  I don't hear much enthusiasm for the other tweaks I mentioned so I will not implement those.
