### ISSUE TITLE
Semantics of the goto statement

### ISSUE THREAD

**Issue by teja5832** [p-org/P#84]
Does a goto from an arbitrary point cause the exit action of the state of the machine to be executed? Also, the below code compiles. Does this mean we have a C-style goto?

~~~
machine Main
{
	start state Init
	{
		entry
		{
			new M(2);
		}
	}
}

machine M
{
	var x: int;
	start state Init
	{
		entry(payload: int)
		{	
			x = payload;
			foo(true);
			x = x + 1; //This line is NOT executed.
		}
	}

	state S
	{
		entry(payload: int){}
	}

	fun foo(b: bool): int
	{
		if(b)
		{
			goto S, 1;
		}
		return 1;
	}
}
~~~

**Comment by desaiankush** [comment]
Yes, goto will cause the corresponding exit function to be executed.
Goto is close to the C-style goto with payload value.
