### ISSUE TITLE
Foreign types and strings for logging

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#9]
It might be useful to support the string type, even if strings are only used for logging, explaining assertions, etc. A project may require us to call an external logging function with a string argument.

**Comment by desaiankush** [comment]
I think providing a string as an argument is possible but providing a
formatted string would be a lot of work.
I guess just providing the normal string would not be enough, you need
formatting string so that you can print p values as well ?

**Comment by paulthomson** [comment]
Normal string literals might be enough. I think Shaz mentioned about treating them as a foreign type. So perhaps this issue can encompass three things:

* Foreign types.
* String literals.
* String literals in assert statements, so I can report the reason of assert.

**Comment by shazqadeer** [comment]
I have checked in support for all of these features.  The print statement in P looks like 

print "shaz";

The assert statement in P looks like 

assert x == y;

or 

assert x == y, "shaz";
