### ISSUE TITLE
testP.bat x64 release, 26 tests fail

### ISSUE THREAD

**Issue by clovett** [p-org/P#91]
Total tests: 606, Passed tests: 580, Failed tests: 26
List of all failed subtests: failed-tests.txt
List of all failed tests (to use for reset): failed-tests-for-reset.txt
To run kdiff3 on outputs for all failed tests: run display-diffs.bat
Tests failed.
Elapsed: 5902.78 seconds

**Comment by clovett** [comment]
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\CastInExprs1\Prt
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\CastInExprs2\Prt
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\CastInExprs3\Prt
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\CastInExprs4\Prt
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\CastInExprs5\Prt
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\CastInExprs6\Prt
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\EnumType1\Prt
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\nonAtomicDataTypes\Prt
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\nonAtomicDataTypes1\Prt
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\nonAtomicDataTypes10\Prt
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\nonAtomicDataTypes11\Prt
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\nonAtomicDataTypes12\Prt
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\nonAtomicDataTypes15\Prt
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\nonAtomicDataTypes17\Prt
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\nonAtomicDataTypes2\Prt
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\nonAtomicDataTypes3\Prt
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\nonAtomicDataTypes4\Prt
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\nonAtomicDataTypes5\Prt
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\nonAtomicDataTypes6\Prt
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\nonAtomicDataTypes7\Prt
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\nonAtomicDataTypes8\Prt
~\Tst\RegressionTests\Feature4DataTypes\DynamicError\nonAtomicDataTypes9\Prt
~\Tst\RegressionTests\Integration\DynamicError\PingPongWithCall\Prt
~\Tst\RegressionTests\Integration\DynamicError\SEM_OneMachine_40\Prt
~\Tst\RegressionTests\Zinger\DynamicError\RaisedNull\Prt
~\Tst\RegressionTests\Zinger\DynamicError\SentNull\Prt

**Comment by clovett** [comment]
ERROR: ASSERT: Invalid type cast
EXIT: 1
Perhaps this is "release" is not doing PrtAssert properly....
but also see:
EXIT: -1073741819
EXIT: -1073740940
One of the Zing logs is longer

**Comment by shazqadeer** [comment]
I am running x64 release now.  I was wondering if this issue repros only with x64.  Are you able to repro it with x86 release as well?

**Comment by shazqadeer** [comment]
/runPrt option seems to be broken now.

C:\Users\qadeer\Work\P\Tst\..\Bld\Drops\Release\x86\Binaries\RunPTool.exe  /runPrt failed-tests.txt /Platform=x86 /Configuration=Release
### Unrecognized option: runprt
USAGE: RunPTool.exe  [options] [file with test dirs]
Options:
    /reset - remove old acceptor file, useful for generating new test baselines
    /cooperative - enable testing of cooperative multitasking
    /platform=[x64|x64] - specify the platform to test (default 'x86')
    /configuration=[debug|release] - specify the configuration to test (default 'debug')
    /runPc - do the compile step only
    /runPrt - run the compiled state machine using PrtTester
    /runZing - run zinger on the compiled output
    /runAll (default)

**Comment by clovett** [comment]
I'll take a look...

**Comment by shazqadeer** [comment]
Noticed another issue.  testp.bat takes args such as /nosync.  It looks like these args are being passed to RunPTool and RunPTool complains as a result.

Time Elapsed 00:02:51.29
Started:  9:41:10.63
Stopped:  9:44:02.14
Elapsed: 171.51 seconds
C:\Users\qadeer\Work\P\Tst\..\Bld\Drops\Release\x86\Binaries\RunPTool.exe  /nosync /noclean my.txt /Platform=x86 /Configuration=Release
### Unrecognized option: nosync
USAGE: RunPTool.exe  [options] [file with test dirs]
Options:
    /reset - remove old acceptor file, useful for generating new test baselines
    /cooperative - enable testing of cooperative multitasking
    /platform=[x64|x64] - specify the platform to test (default 'x86')
    /configuration=[debug|release] - specify the configuration to test (default 'debug')
    /runPc - do the compile step only
    /runPrt - run the compiled state machine using PrtTester
    /runZing - run zinger on the compiled output
    /runAll (default)

**Comment by shazqadeer** [comment]
Chris has already fixed the issue of 26 failing tests with x64 release build.  I have created a new issue for /runPrt problem.  So, I am closing this issue.
