### ISSUE TITLE
/runPrt option to testp is broken

### ISSUE THREAD

**Issue by shazqadeer** [p-org/P#92]
/runPrt option seems to be broken now.

C:\Users\qadeer\Work\P\Tst..\Bld\Drops\Release\x86\Binaries\RunPTool.exe /runPrt failed-tests.txt /Platform=x86 /Configuration=Release

Unrecognized option: runprt

USAGE: RunPTool.exe [options] [file with test dirs]
 Options:
 /reset - remove old acceptor file, useful for generating new test baselines
 /cooperative - enable testing of cooperative multitasking
 /platform=[x64|x64] - specify the platform to test (default 'x86')
 /configuration=[debug|release] - specify the configuration to test (default 'debug')
 /runPc - do the compile step only
 /runPrt - run the compiled state machine using PrtTester
 /runZing - run zinger on the compiled output
 /runAll (default)

**Comment by clovett** [comment]
[Fixed](https://github.com/p-org/P/commit/ebe4aa850bef0e9e02c7a4b7f7e746466dc712e6),
