### ISSUE TITLE
Input to DgmlLogViewer 

### ISSUE THREAD

**Issue by t-rasmud** [p-org/P#93]
What is the command to generate the P log file that can be given as input to DgmlLogViewer?

**Comment by clovett** [comment]
DgmlLogViewer is a limited hack, it just parses output from some of the LogHandler functions that call PrtPrintStep and attempts to reassemble what happened from there.  There is a better way now using DgmlMonitorLib.  See the PingPongSimple for example of how to use it.  It can stream the events to Visual Studio if you have the DgmlTestMonitor VSIX extension installed (use the Connect method), or it can save the DGML to a file.  I just pushed some improvements to DgmlTestMonitor so it can be used without VS.
