### ISSUE TITLE
Sequence Inserts

### ISSUE THREAD

**Issue by teja5832** [p-org/P#95]
What would happen in the following case? Will the gaps in the middle of the sequence be filled with the default value for int? [The zing model does not, indeed throw an error.]

var s: seq[int];
s += (0,1);
s += (5,13);
assert s[3] == 0; //Default for int.

**Comment by desaiankush** [comment]
This is lead to an error in P.
For Seq += (Index, Value)
0<= Index <= sizeof(seq).
0 -> add at the start
sizeof(seq) append at the end.

**Comment by teja5832** [comment]
Thanks!
