### ISSUE TITLE
Integrate build tracking system

### ISSUE THREAD

**Issue by thisiscam** [p-org/P#97]
Right now it's very easy to break P's cross platform build during activate development; a good thing to do is to setup a build tracking system on this repo so that we can keep up-to-date changes for different platforms.

It should be very helpful in long runs.

[jenkins](https://jenkins.io) Might be a good place to start.

**Comment by ankushdesai** [comment]
We have azure pipelines integrated. But we need to update it so that it can run the regressions as well each time someone makes any commits.

**Comment by ankushdesai** [comment]
The azure pipelines now build P on all the three platforms. It also runs the regressions on the windows platform.
